### ISSUE TITLE
Add link preview 

### ISSUE THREAD

**Issue by thundergreen** [kriztan/Pix-Art-Messenger#113]
Would be nice having link preview for twitter YouTube github etc

Kaiwa has one and its pretty nice :)

**Comment by kriztan** [comment]
This could be a privacy problem, but we can do it configurable.

**Comment by thundergreen** [comment]
That would be awesome

Am 19.02.2017 07:24 schrieb "Christian Schneppe" <notifications@github.com>:

**Comment by Echolon** [comment]
What's the privacy issue about this again?

**Comment by kriztan** [comment]
A preview makes it neccessary to open the website, you leave traces in the webserver logs and any possibly integrated tracking services would count your access. This is what I meant with privacy issue.

**Comment by thundergreen** [comment]
we finally get link preview?? WOW!!!  That's a 2 year old request and it now is implemented.. THANKS CHRIS!!! :)
