### ISSUE TITLE
Add ad hoc commands for admins 

### ISSUE THREAD

**Issue by thundergreen** [kriztan/Pix-Art-Messenger#114]
Adding ad-hoc commands would allow dedicated admins to manage their server without having gajim or co with them. Also server messages to all users is a very nice feature

**Comment by Echolon** [comment]
I think, that's not a priority for Pix-Art at the moment :/

**Comment by kriztan** [comment]
This is on my priority list at the very very lower end.

**Comment by kriztan** [comment]
I'm closing this, because it is a nerd function.
