### ISSUE TITLE
Rename APP

### ISSUE THREAD

**Issue by thundergreen** [kriztan/Pix-Art-Messenger#117]
This app is going to be a great substitute to WhatsApp. Why not calling it 

ThatsApp?

**Comment by kriztan** [comment]
I think the `ThatsApp` is phonetical too similar to `WhatsApp` so this could make license problems.
But I'm open for other (shorter) names. 

What about `ThatsIM`?

**Comment by thundergreen** [comment]
That's im is nice! Short and direct

**Comment by kriztan** [comment]
We will keep this in memory for version 2.0.0

**Comment by thundergreen** [comment]
What about Th@t's!M

**Comment by thundergreen** [comment]
Th@t's!M™
Th@t's!M°
Th@t'sMe

**Comment by Kelvino9** [comment]
**ThatChat** would be a nice rhyming name for this app.

**Comment by thundergreen** [comment]
@Kelvino9
 Thanks for participating here ..  I will forward those to the Dev and see what he thinks . U might want to join us in the muc?

**Comment by Echolon** [comment]
Hi,

I don't have any better suggestions at the moment, but I think we should put some more efforts and creativeness into a new name - may combine it with a new logo, too or so. But "That'sIM" ... I mean what shall it stand for? :/

There is no rush for this, but some more suggestions would be good.

**Comment by Echolon** [comment]
May we could just call it "PIX" - easy, short & simple

(Could even mean something - but doesn't have to!: **P**erfect **I**nstant-Messenger for **X**mpp )

:D

**Comment by kriztan** [comment]
Without thinking a lot about your suggestion I like it @Echolon

**Comment by Echolon** [comment]
Hm, this is what I got in the Playstore. But why not? Otherwise we call it PIX, but in the App Store the official title is "PIX (Pix-Art XMPP Messenger)" or "PIX - XMPP Messenger"

![selection_052](https://user-images.githubusercontent.com/29168011/36346520-47d20796-1440-11e8-8836-a53d3196abb0.jpg)

Anyway, I prefer a simple and easy to remember name - because you are making an easy and usable messenger.

**I suggest other can vote up or down my previous comment.**

**Comment by Echolon** [comment]
Got another one: PIXIM   (would keep capital letters)

**Comment by Echolon** [comment]
Hmm, getting inventious :dagger: 

What about: PIXIT  (again, would keep capital letters)

**Comment by Kelvino9** [comment]
Really liking @Echolon idea of renaming the app to **PIXIM**, **pixIM**, **PIXim** allot.
It includes the the beginning and the ending of Pix-Art Messenger and yet is stil muchl shorter and good sounding.

**Comment by Echolon** [comment]
@Kelvino9 thanks - still think PIX is very simple  - ID could just be @pix.im - for future registrations.
If we rename - should be better down now, than later, or?
Easy names, are easier to remind for people, especially, when handling with IDs.

The .im think is maybe a bit old school and actually not necessary anymore

**Comment by Kelvino9** [comment]
The im part is actually what I like the most of your suggestion as it is the abbreviation for Messenger.

And with PIX still in the name it is an overall clever short form of Pix-Art Messenger which naturally reminds me allot of those company branded messengers like AOL, Microsoft and especially Facebook.

**Comment by genofire** [comment]
so you already **pix**me :+1:

**Comment by grinapo** [comment]
It is beneficial to check _google_ and _app stores_ before conjuring up a name. 
I would definitely advise against an unsearchable non-unique name like "pix".
(I decided not to mention completely unique words like "pixxage" [a la message], mainly because my brain is on low battery now.)

**Comment by Echolon** [comment]
@grinapo Why is it unsearchable?

But if so, then I'd suggest to make it P I X I M

But not with a dot PIX.IM, thats pretty old school and should only be used for a new domain  @pix.im

see also #203

**Comment by grinapo** [comment]
@Echolon Unsearchable names are usually which are too short to be unique (less than 4 letters, usually, unless it's a really weird combo); those contain separators ignored by search engines (like dash [-], dot [.], and various other punctuation); and obviously those which match a soundex of a popular search (like most things containing, say, 'pixa' -> 'pixar'). 
You do not have to believe me -- go to google and bing, and try your favourite. If there is _no_ result at all, you win; if you have only non-matching results, you may be still good; if there are plenty of query-relevant results then you are basically fscked. Just as in case with "pix" (324 million results), "pixim"  (122 thousand with relevant companies and products) or like. 

(I don't immediately see how issue 203 would be relevant in this discussion.)

**Comment by Kelvino9** [comment]
I think we can ultimately close this issue.
There hasn't been any serious intention or direction in months in renaming the app into something nicer or better.

**Comment by trevuchet** [comment]
I suggest the app name be

**Jabber Texting**
**PIX Texting**
**PIX Converse**

Escape the notion of IM, chat, and messaging.

Do stick closely to **texting**.

**That Texting**


Otherwise people will whine, "just use normal texting".  See, they are attaching an adjective to texting already.  Although some people complain, "why can't you just use texting like a normal person".

I block all sms at the provider level.

**Comment by intika** [comment]
Search won't be a problem because the app is getting popular, and when it is enough, google etc will automatically list it first what ever the name is

**Comment by ostasevych** [comment]
Pix-Art is fine, I think :)

**Comment by Kelvino9** [comment]
@kriztan please close this issue as there is no serious means in changing the name. This issue was created over three years ago and it got nowhere.

**Comment by Echolon** [comment]
@Kelvino9 @kriztan 

I'd prefer to leave it open. At least one suggestion got a high ranking. And I personally think there could be overhaul help the popularity. 

As there not much issues. I would leave it open please.

**Comment by Kelvino9** [comment]
@Echolon, @kriztan mentioned many times in the Pix-Art chat room that he would no longer change the name of Pix-Art Messenger because of its popularity. So actually that decision has been made for some time. That's why I suggested to close this issue.

**Comment by kriztan** [comment]
I've decided to close this now because I won't change the name.
