### ISSUE TITLE
import backup should reset OMEMO keys

### ISSUE THREAD

**Issue by kriztan** [kriztan/Pix-Art-Messenger#129]
Due to problems with OMEMO after restoring a backup, the import should reset the OMEMO key.

**Comment by vanitasvitae** [comment]
OMEMO sessions break, if messages are sent and received after the backup was made. That causes the sessions on both sending and receiving side to advance, bringing them out of sync with the backup. Restoring the backup then breaks the session, so this is a real issue.

**Comment by vanitasvitae** [comment]
Correct me if I'm wrong, but it should be enough to just delete the sessions and prekeys, but keep the identity key.

Ideally the app should send PreKeyMessages to every device it had a session with before to initialize new sessions. That way the contacts should not have to verify the fingerprint of the identitykey.

**Comment by kriztan** [comment]
Thank you for your report. But the main problem I see is, that without completely purged OMEMO keys, you could break a lot of things, if anybody tries to import a backup in multiple devices. All the devices would have the same device id, what must not be. So my preferable way is an OMEMO reset. And yes, you and your contacts have to verify each other again.

**Comment by vanitasvitae** [comment]
>All the devices would have the same device id

Why is that?

**Comment by kriztan** [comment]
In the database the device id is stored. Importing a backup on multiple devices would restore the device id too. So the whole OMEMO keys including the device id should be purged I think.

**Comment by kriztan** [comment]
And for security reasons it would be better to tell your contact that you've imported a backup and that the keys should be verified again instead of silently move to a new device or import everything. If anybody could get your backup and is able to import it correctly, he could silently write and read encrypted messages to and from your contacts and they wouldn't know that it is not you.

**Comment by vanitasvitae** [comment]
>In the database the device id is stored. Importing a backup on multiple devices would restore the device id too. So the whole OMEMO keys including the device id should be purged I think.

Ah now I get what you mean. I thought you are talking about multiple accounts being restored on one device.

Yeah, restoring the same backup on mutliple devices is bad, but that should be common sense.

Securitywise, I think it hurts more to require users to again verify their fingerprints (which they likely will not do), than silently move to a new device. I mean, in what case does that hurt? If an attacker gets the backup, it might be older and is in that case nearly useless apart from a tiny time window (messages sent between moment of backup and first reply sent afterwards). The attacker gets no sensitive information what so ever.

The backup only comes in handy for an attacker, if you use another set of keys than the backed up ones, so that they can put the backup device back on the device list. In this case they can snoop messages, but the user can also recognize the attack by checking their device list.

**Comment by peterjw** [comment]
I vote for keep OMEMO keys with the backup - I mean, this is what "backup" means, isn't it? Forcing your contacts to accept new keys too often will just lead to people accepting every key they are asked to accept, circumventing common-sense checks whether it is from a trustworthy source or not.

**Comment by kriztan** [comment]
I've recognized some strange behaviour after importing all keys. Some of the sent and/or received messages could not be decrypted or wasn't sent/received correctly. At the moment I can't say, what's the problem.
There is a second sideeffect: if you try to import a backup on a second device while your previously back uped device is still online. This will break the en-/decryption and this should be forbidden programmatically.

**Comment by vanitasvitae** [comment]
I vote for deletion of the keys upon backup. OMEMO keys are not meant to be backed up conventionally, but rather for identity transfer from one device/installation to a *new* one.

**Comment by peterjw** [comment]
@vanitasvitae Sorry, I don't get it.
Didn't you argue that deleting keys is not neccessary above?

> OMEMO keys are not meant to be backed up conventionally,

What do you mean by "not meant to be backed up conventionally"? Why would you not restore the keys from a backup after some crash or data corruption in the app/on the phone?

> I vote for deletion of the keys upon backup.
> [...]
> for identity transfer from one device/installation to a new one.

Are you saying, you would delete them in the app on the _old device_ to make sure, they are **only** on the _new one_ after importing the backup?

**Comment by zz-ha-dum** [comment]
Is the problem more akin to lack of key signing like OpenGPG affords?  omemo Keys seems like an overly generous term in this context.

**Comment by peterjw** [comment]
@zz-ha-dum 
> Is the problem more akin to lack of key signing like OpenGPG affords? omemo Keys seems like an overly generous term in this context.

To my understanding, it's more a problem of loosing session keys for perfect forward secrecy and problems in restarting the session.
Regarding "...  seems like an overly generous term ..." - are you familliar with OMEMO at all? It's a very specific encryption protocol and this issue tracker is about a very specific implementation as well.

**Comment by kriztan** [comment]
Not needed anymore because of https://github.com/kriztan/Pix-Art-Messenger/commit/72a6e378646f0d42cce97616bd2f01b84870049c

**Comment by 7usr7local** [comment]
Great news!
