### ISSUE TITLE
Availability in F-Droid and PlayStore

### ISSUE THREAD

**Issue by BlauerHunger** [kriztan/Pix-Art-Messenger#130]
I think Pix-Art Messenger is a nice thing, but why isn't it available through F-Droid?

**Comment by kriztan** [comment]
It can't be built without a valid api key for maps. So f-droid servers can't use my code without adding their own keys. But you can add this third party f-droid repo https://android.izzysoft.de/repo which uses my published apk files.

**Comment by kriztan** [comment]
I've added a hint in the readme to the izzysoft f-droid repo.

**Comment by Echolon** [comment]
Maybe reopen, as we had the chat discussion? - maybe change title for + PlayStore port, too

**Comment by kriztan** [comment]
Since yesterday, I've uploaded Pix-Art Messenger into the [Google PlayStore](https://play.google.com/store/apps/details?id=de.pixart.messenger)

**Comment by Echolon** [comment]
Guess can be finally closed now :)

**Comment by mightyBroccoli** [comment]
There are some issues with this. I installed the client from Google Play store and I still get the "unknown sources are not allowed window" popping up all the time. This is really annoying as the version does not need that.
Also the update function shouldnt be there if installed from GPlay.
Exept from that I love it. 🦄

**Comment by kriztan** [comment]
@mightyBroccoli this has been fixed with 3bb696a5d6c057b6d5df178fa97722680c10580b

**Comment by mightyBroccoli** [comment]
thank you this is awesome 👍

**Comment by licaon-kter** [comment]
What's the difference between the "open" and the "standard" version?

**Comment by IzzySoft** [comment]
@licaon-kter None anymore – which is why the "Open" version will no longer be updated. Historically, with the "Open" you could pick the XMPP server of your choice, while the "Standard" automatically picked Christian's server. For quite a while now, both versions are identical and have both ways implemented.

As it makes no sense to maintain two identical apps, Christian will no longer build the "Open" version – so if you're using that, you should switch. Also see the description of the "Open" version [in my repo](https://apt.izzysoft.de/fdroid/index/apk/de.pixart.openmessenger) for details.

**Comment by licaon-kter** [comment]
I was using the one that your repo provided (apparently "open"). Today I saw another version added too, hence my question.

Thanks, I'll switch.

**Comment by IzzySoft** [comment]
@licaon-kter could you please verify whether the "Standard" version can import a backup made by the "Open" one? If so, I'd add that as hint. Unfortunately, Christian didn't answer that question (yet).

**Comment by kriztan** [comment]
I've answered this question yesterday @izzy. You can make a backup with the open version and import this with the standard version.

**Comment by licaon-kter** [comment]
@IzzySoft I did not care about the backup :)

**Comment by IzzySoft** [comment]
@kriztan Oh? Must have missed it then (or that mail didn't reach me). I'll integrate a hint then with the "Open" version that this is the way a user can migrate without losing data or having to re-configure everything:

> For a migration without having to reconfigure everything, create a backup first (from within Pix-Art "Open"), and restore that into Pix-Art "Standard".

Wish there were something similar for a switch from Conversions …

Please let me know when I shall drop the "old Open" from my repo. I'd suggest to keep it for 1..2 months and then drop it end of May? For now, I've renamed the "Open" to "Pix-Art Messenger (deprecated)" – to make it easier for users to pick the right one.

**Comment by genofire** [comment]
Any new information for the F-Droid ?

**Comment by grinapo** [comment]
Apart from that it's on it? ;-)

**Comment by kriztan** [comment]
Thanks @all
