### ISSUE TITLE
Start conversation view needs account/settings options

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#134]
#### General information

* **Version:** 1.18.1
* **Device:** Xperia
* **Android Version:** stock 6.0.1

#### Steps to reproduce

1. Install/clean app
2. Register a new account (or add one I guess)

#### Expected result

Be able to add contacts/conferences
Be able to change settings/accounts

#### What do you see instead?

No way to access settings/accounts, only options are Scan/Hide Offline

Those two might need to be added [here](https://github.com/kriztan/Pix-Art-Messenger/blob/7c49e47659897c80d7e1b5998c66a7caa97fedc6/src/main/res/menu/start_conversation.xml) and elsewhere

**Comment by kriztan** [comment]
Thanks @licaon-kter, I'll add the menu items.
