### ISSUE TITLE
Re-enabling foreground service control

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#138]
Any chance of reverting https://github.com/kriztan/Pix-Art-Messenger/commit/0f4ccb64ba03630568b20c44814908c06c7aa88e ?

Yes, I know Android forces you to have it, but good behaving ROMs don't kill apps out of the blue, hence having a permanent useless notification is not nice.

**Comment by kriztan** [comment]
I'm going to add an option to disable the foregroundservice in future. This option will be placed in expert options.
