### ISSUE TITLE
Separate received and sent files 

### ISSUE THREAD

**Issue by kriztan** [kriztan/Pix-Art-Messenger#140]
Note to self: separate send and received files in different folders

**Comment by Echolon** [comment]
Maybe switch of saving my own send files again in a new folder. I hate it in Conversations and it just costs extra memory.... or make it optional.

**Comment by tmolitor-stud-tu** [comment]
yes please!

**Comment by tmolitor-stud-tu** [comment]
Seems to be broken again :(
