### ISSUE TITLE
"Conference" or "Group chat"

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#158]
Will Pixart diverge and keep the old title?

Context: https://github.com/siacs/Conversations/commit/3dbe5db44b508c1cf71407d4cbc98acf1a8763c8

**Comment by kriztan** [comment]
I'm going to change this in one of the next releases.

**Comment by kriztan** [comment]
This should be done on the translation platform https://crowdin.com/project/pix-art-messenger

**Comment by licaon-kter** [comment]
Yes, for other languages.

The base `strings.xml` is English and that one can't be edited on Crowdin, so you first do it here ( PR #168 ) and then push it to Crowdin.
