### ISSUE TITLE
Location sharing - swap/integrate non-Google

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#163]
Since your app is not (yet?) in the Google Play store I find it odd to depend on Google services for location sharing, given that this ( https://bitbucket.org/SamWhited/opensharelocationplugin/src ) alternate location plugin works ok with OpenStreetMap.

Any chance to integrate it so F-Droid builds the OSM version and you (and future Google Play versions) build the Google Maps one?

**Comment by kriztan** [comment]
Yes, the integration of OSM is planned and on my to do list. The small location previews are using static OSM images already in the chats.

**Comment by kriztan** [comment]
OSM integrated with 8cf20a8222ee1102edbe47ebec312862042bb0c9
