### ISSUE TITLE
FR: Inband GIF support

### ISSUE THREAD

**Issue by Echolon** [kriztan/Pix-Art-Messenger#170]
Would probably convince me to migrate from Conversations to Pix-Art :)

**Comment by kriztan** [comment]
What do you mean exactly? Gif files are supported and they will be played like a video.

**Comment by Echolon** [comment]
I meant rather inband GIF support. That you see the moving GIF directly in the chat view.

**Comment by MalevolentGrin** [comment]
If animations are enabled I would appreciate a user option to not-show animations inline (unless clicked)
