### ISSUE TITLE
Idea: More individual profile view

### ISSUE THREAD

**Issue by Echolon** [kriztan/Pix-Art-Messenger#171]
Hi,

my idea is about a customization of the profile window. 

It would be cool to see a bigger picture of the user, and get some more information about the person - Things they might provide on their own; address, phone number, more text... what ever. Additionally, there you be a banner picture like you have on e.g. Twitter or see in the software presentation/window of Fdroid Store.

Add your ideas. Feel free to change the title if you have a better one.

**Comment by kriztan** [comment]
A bigger contact picture is possible, but where to fetch the information from you want to have? A Conversations/Pix-Art Messenger environment does not allow adding more information at the moment. Or should we show information from the address book? But therefore you need to save your contacts jabber addresses inside your address book to fetch these information with the messenger. I doubt that many people doing this for all their contacts.

**Comment by brighterness** [comment]
When clicking my own avatar inside a chat I would like to see my avatar at the size it was when I accepted the upload for publishing.

>  jabber addresses inside your address book 

I have quit doing this as there is no option for me to choose

* use address book contact's image

OR

* use avatar set in JID by remote user

OR

* use avatar I set for JID in app 


I would be DELIGHTED to have this extra control... then resume encouraging people to add JID to android address book.

**Comment by Echolon** [comment]
https://github.com/kriztan/Pix-Art-Messenger/issues/423
