### ISSUE TITLE
FR: Tutorial for newbies

### ISSUE THREAD

**Issue by Echolon** [kriztan/Pix-Art-Messenger#172]
Hi,

I would like to initiate a discussion about a tiny guide for new users.

The guide should:
- Introduce new users to XMPP (adavantages!)
- Make aware of it's privacy standards and encryption
- Give a hand in the beginning.

A visual and intuitive design would be appreciated. Examples and technological ways are e.g.

- Silence overlay welcoming on first start
- Overlays like this: https://github.com/KeepSafe/TapTargetView
- https://informationisbeautiful.net/

Of course everything should be possible to skip and switch off instantaneously.

I think a good start would be, if this is necessary or not? Then we could discuss the content and finally how to implement.

Of course, I think we need it, as
- most people havent heard about the network
- dont know that there is a secure and privacy caring software in their hand
- they should be supported as they get in touch with the software

**Comment by kriztan** [comment]
This is a very nice idea. At first I would like to add some usefull hints to the wiki pages 

https://github.com/kriztan/Pix-Art-Messenger/wiki

My wiki pages can be created and edited by any github users at the moment. So feel free to start working on it.

**Comment by Echolon** [comment]
Monal reacted to my suggestions with their own idea: https://monal.im/blog/the-welcome-screen/

I already drafted something, but haven't had the time to bring it to the screen yet. but will definetly do it

**Comment by Echolon** [comment]
New point:

The last screen will welcom the user, but ask him a few more questions with check marks or toggle:

Just a few details which might be relevant:

- Shall other users see that you are online? (Differ from presence, maybe not, as XMPP is not that 100% reliant)
- End-to-End-Encryption always active?
- Dark mode active?

What else could it be?

**Comment by Echolon** [comment]
https://xmpp.org/extensions/xep-0379.html

https://xmpp.org/extensions/xep-0401.html

**Comment by Echolon** [comment]
Lots of clients ask their users about specific settings. Could be handled here as well

**set omemo encryption at the beginning when log-in.** #338

**Comment by Echolon** [comment]
Hi @kriztan,

I'm very happy to see your work for a newbie introduction! AWESOME! :heart: 

As this is beta status, I use my chance to make some hopefully helpful advises. My interest are basically about two things:

- Keep it simple, but smart. The user should understand the new (XMPP) environment, but should not read lots of text or feel overwhelmed. Therefore less text and clear active and positive statements are easier to go I think and also help a lot to have a good feeling after installing the app. The user should understand what is different in here.

- Split introduction and tutorial/explanations. The introduction should be rather general, about Pix-Art and XMPP and also the advantages! The explanations how to use the app should actually not be necessary in the best case, but also not in the start.

Therefore my first suggestion is to use something like this: https://github.com/KeepSafe/TapTargetView
This should focus on details which might not be clear in the beginning. For example, clicking or pressing avatars. I would put the following slides into an explanation pop-up (TapTargetView):
- Chat starten
- Benutzer wählen
- Chat details

Secondly, I will give some examples for the first screens. I suggest do keep it down to 3 or 4 slides!

To begin with, I edited the welcome screen:

<img src="https://user-images.githubusercontent.com/29168011/65544664-fd62e400-df13-11e9-8c25-10298ccf3924.jpg" width="300">
Sorry, everything is in German. As you can see I reduced the text in every screen. I also can only recommend to every XMPP developer to tell the users what they are in (XMPP/Jabber :smiley: ). At least, just to spread the word!

Here is the next screen. You see, I like clear statements. And rather active language.

<img src="https://user-images.githubusercontent.com/29168011/65544839-6cd8d380-df14-11e9-9890-38ff3ee634fe.jpg" width="300">

Last but not least, the user gets a first overview, nothing else. We don't want any too specific explainations :wink: 

<img src="https://user-images.githubusercontent.com/29168011/65544846-719d8780-df14-11e9-83df-eef0f8106c3d.jpg" width="300">

Thirdly, I would use the TapTargetView to explain that OMEMO is the open-source encryption they use. And, as recommend in here https://github.com/kriztan/Pix-Art-Messenger/issues/227, I would actually only keep it down to encrpted and not encryptioned. People do not understand anything else effectively.

Thanks for our great progress Chris!

**Comment by kriztan** [comment]
Thank you @Echolon 
I#m going to improve the intro with your suggestions

**Comment by Echolon** [comment]
Hi @kriztan,

thank you for your efforts and reworking the screens. On the one side I am very happy to see many improvements, also mine you included. On the other side I still want to recommend to overthink some points. I hope that won't affect my ideas, but you are free to go for anything you want of course!

- Number of slides: I see that you want to ensure that everyone understands the new environment and that is of course very very important to consider (this is why I recommend you app often enough!). Still, I think we should **limit the explaination to the very new things** in Pixart.
I count by now **12 slides**. That's is a lot I think, too much to be honest. I would try to reduce it to **6, or rather 4 to 5 slides**.

Why am I going for less? Imagine someone is just opening new to their.. thrid... maybe fourth messageing app (excluding email :smiley: ). Likely, they know how those basically work (chatting, sharing etc). Furthermore, they don't want to swipe through a presentation.

I would like to suggest to do the following:

- As said reduce the slides - take out the obvious ones - and **as a compromise use the detailed explainations only in a re-run of this introduction** (so, via the menu they can re-run the introduction).

- I would keep only the following slides in the default presentation after installation:

1. Willkommen
2. XMPP/Jabber (maybe you still can combine them as I suggested)
3. Privatssphäre (I would combine it with the information of "Optionale Berechtigungen")
or
4. Reduce "Optionale Berechtigungen to one slide. I'm not sure if that is really necessary. As said in the previous post: Let's focus on what Pix-Art does right. Make more simple active statements, not explainations --> Expanded Introduction.
4. You said in the first or second statement that you will ask the user for each permission. I think that also makes the two "Optionale Berechtigungen" a double, or?
5. Explainations about the ID what you have there, also combine if possible.

- Maybe it also makes sense to **help people with creating MUCs** (we shouldn't call it like this). My friends often somehow seem to have problems with the UI (no offence).

- What I basically mean about reduced and valueing statements (not design :laughing: ) can be seen in Monal: http://monal.im/blog/the-welcome-screen/

If you want me to be more detailed with screenshots again, I am happy to do so!

**Anyway, what ever you choose to do, I think the introduction screen is a very important and milestone step in XMPP.** :+1:

**Comment by kriztan** [comment]
added via 041351b176843d9ba0be2813a16e4623ebfeee65, 59f392a17aed84019a51558aa582a66f567438e3, 72f2b8650ec86af524dcdefd81d8037388a60622
