### ISSUE TITLE
Should Barcode Integrator strings be translated?

### ISSUE THREAD

**Issue by esu23** [kriztan/Pix-Art-Messenger#184]
Should the [Barcode Integrator strings](https://github.com/kriztan/Pix-Art-Messenger/blob/e7d13398915544c3b8cf5e1ac60873223495c18c/src/main/java/de/pixart/messenger/utils/zxing/IntentIntegrator.java#L117) be translated?

I refer to those ones:

<img src="https://user-images.githubusercontent.com/20012803/36636335-3436665c-19c5-11e8-9884-632bc2163445.jpg" width="360" height="618" />

**Comment by kriztan** [comment]
Yes, we should translate them too.

**Comment by esu23** [comment]
zxing barcode scanning integrated since 2.0.0 beta
