### ISSUE TITLE
Can we add it to F-Droid?

### ISSUE THREAD

**Issue by oyren** [kriztan/Pix-Art-Messenger#185]
see title.
also a APK download without google play would be nice.

**Comment by kriztan** [comment]
partly duplicate of #130 
This app is in Izzys F-Droid Repo. Until now, I've not yet added it to the main F-Droid repo. Feel free to do that. I'll upload some screenshots. Please use the `standard` version. The `open` version will be removed in future.

**Comment by oyren** [comment]
Crap, I didn't see that.
