### ISSUE TITLE
WebRTC, Jingle, VoIP/ Videocalls

### ISSUE THREAD

**Issue by c-93** [kriztan/Pix-Art-Messenger#188]
Hello together,

I think this could be quiet complex on a mobile platform, but other projects (like the jistsi android messenger) already achieved this years ago.
I would suggest to enable Jingle (XMPP voice & video calls) in Pix-Art-Messenger or Conversations. Maybe I have time next semester to branch and start the development. I think there are already some open source libraries available which "simply" have to be implemented in the project.

Greetings

**Comment by Echolon** [comment]
@raudy66 

Hi, and thanks for your approach. As this is a very challenging task, your might wanna read this first: 
https://github.com/siacs/Conversations/issues/1234
https://github.com/siacs/Conversations/issues/1139
https://github.com/siacs/Conversations/issues/1646

Hope this doesn't put you down. Anyway, there was a big discussion.

Furthermore, if you are quick - apply here at Google Summer of Code: https://summerofcode.withgoogle.com/
for this: https://summerofcode.withgoogle.com/organizations/5223357386063872/

> Jingle encrypted A/V calling
> 
>     Software Project: Conversations
>     Software URL: conversations.im
>     Software VCS URL: github.com/siacs/Conversations
>     Software Description Conversations is a state of the art mobile instant messaging client for Android. It provides a modern user experience and is on top of the current developments in XMPP standards.
>     Brief explanation: The ability to make voice and video calls is by far the most requested feature for Conversations. With Jingle there is a standard extension in XMPP to negoitate P2P audio and video sessions. Implementing video calls faces many challanges. Not only network and bandwidth wise but also UX wise.
>     Quite frankly this is a rather challenging project. We aim to actually merge the code that comes out of GSoC and we can't merge the code if the UX is bad (either because of too many edge case where it simply doesn’t work or because it looks terrible.)
>     Expected results:
>         Make libwebrtc build in Conversations
>         Setup some basic A/V calls between two Conversations clients
>         Translate the SDP output of libwrtc to Jingle syntax
>         (Re)negoitae the session on network switches or screen rotations
>         Implement a great accept call and call UI
>     Difficulty: Very hard
>     Implementation Language: Java/Android
>     Contact Details: MUC at gsoc@conference.conversations.im




Would be great if you could make a first step. Maybe others will join!

**Comment by raudy66** [comment]
Unfortunately I only have 2 weeks semester break instead of the 3 months stated by google. But anyway, this might also be done during the semester. I'm asking my friends for support.

**Comment by raudy66** [comment]
I found two friends and we like to work as a team on this feature for conversations/ Pix-Art. The application for the gsoc will be sent to google soon.

**Comment by kriztan** [comment]
That's very nice 👍

**Comment by Echolon** [comment]
Awesome guys! All the best!
Take care about their deadline for application, please!

**Comment by raudy66** [comment]
Thanks. Most of the gsoc application is already written ;)
One last possible problem might be, that Google usually only supports single students and not teams.
Anyway we give it a try.

**Comment by Echolon** [comment]
@raudy66 or apply as single student and split the money by yourself. Would be a shame if this is wont be accepted because your are "too" much people....

**Comment by raudy66** [comment]
Still waiting for their decision.

**Comment by Echolon** [comment]
@raudy66 So you haven't been picked? What happened?

**Comment by raudy66** [comment]
Got their decision yesterday. Neither me nor my friends nor any other group got this topic. They are all working now on other topics. I instead assigned in two obligatory projects at university. But it would still be great to have this feature.

**Comment by Echolon** [comment]
Hey, yes, got it from the Conversations MUC, that all were rejected, which makes me kinda suspicious (but I told him).

Yes - and I suggest the following to you: Create a self-organised project on VoIP only - ask for donations (Liberapay offers continous donations) and just do it yourself with your friends. I would spend some money. others, too hopefully.

If you would just do one-step in the right direction, that's probably the best you can achieve.

Thanks anyway, all the best!

**Comment by knoy** [comment]
Hello,
I would like to point to your attention to aTalk ( https://github.com/cmeng-git/atalk-android ) which seems to be based on a combination of LibJitsi and Conversations and uses a variety of libraries (ffmpeg, h264x, openssl) to make ZRTP encrypted audio and video calls over XMPP

**Comment by Echolon** [comment]
FYI for next year: https://rishiraj22.github.io/articles/2018-05/gsoc-selection-journey

**Comment by muppeth** [comment]
Friend of mine hacked bundled jitsi and conversations together. I think its a good starting point as it just works, and on desktop side you get a link to jitsi site. also in options you can specify which instance you want to use. Clean, simple and most of all working:
 https://git.geekyboo.com/newbie/Conversations-JitsiMeet/commit/72ad2f1333d13aee32d1fbcc1a0cebe7b4b1a3fe
(excuse slef signed cert).

**Comment by myluckyapps** [comment]
@muppeth, I have tested it and its working 👍

**Comment by muppeth** [comment]
I think it needs to be updated for the new UI. I hope conversations would implement it, I hope if more people push / request it, it might have more chances to get into upstream. I shared that idea on conversations muc but havent get around submitting a request on github (please do so if you want).

**Comment by brighterness** [comment]
@knoy 

I installed [aTalk](https://github.com/cmeng-git/atalk-android/issues/17) on my sandbox tablet two nights ago.  I have not had time to play with it yet.

**Comment by tmolitor-stud-tu** [comment]
Why not use WebRTC?

Some thoughts and a list of useful links and resources I collected last year can be found in this issue over here:
https://github.com/ChatSecure/ChatSecure-iOS/issues/738

**Comment by muppeth** [comment]
I would still argue for jitsi implementation. Its not perhaps native but:
1. Should be easy to add to pixart (harder to conversations given that it should be a plugin simce i guess inputmice would not want to merge it upstream)
2. Would work everywhere. This is the most pragmatic point imo. If you implement native webrtc you would have to make sure every other client supports it. Meaning that whwn for example on dino or conversations you wouldnt be able to. Already now with pidgin and gajim its nearly impossible to call as it all depends on so many aspects. With jitsi its simple. If your client doesnt have some form of implementation (though special buttons etc) you get a url which will work as long as you have a browser. That means that it will work for anyone. Not to mention the fact you can just deploy your own jitsi server as easy as just apt-get'ting it.

**Comment by tmolitor-stud-tu** [comment]
There are WebRTC SDKs out there for virtually every platform and language.
WebRTC gives us more interoperability not less and it even allows 
webapplications like jsxc or converse to implement voice/video calling.


Am Freitag, 26. Oktober 2018, 14:57:04 CEST schrieb muppeth:
> I would still argue for jitsi implementation. Its not perhaps native but:
> 1. Should be easy to add to pixart (harder to conversations given that it
> should be a plugin simce i guess inputmice would not want to merge it
> upstream) 2. Would work everywhere. This is the most pragmatic point imo.
> If you implement native webrtc you would have to make sure every other
> client supports it. Meaning that whwn for example on dino or conversations
> you wouldnt be able to. Already now with pidgin and gajim its nearly
> impossible to call as it all depends on so many aspects. With jitsi its
> simple. If your client doesnt have some form of implementation (though
> special buttons etc) you get a url which will work as long as you have a
> browser. That means that it will work for anyone. Not to mention the fact
> you can just deploy your own jitsi server as easy as just apt-get'ting it.

**Comment by muppeth** [comment]
And yet barely anyone in last 20years did it. I just want to be pragmatic with this. Yes native jingle webrtc would be awesome but since for some reason barely anyone did it, why not in the mean time get some low hanging fruit with jitsi. 
Imo i do agree native solution should be the goal, but why not have a solution ready here and now for the time being?

**Comment by tmolitor-stud-tu** [comment]
...WebRTC *is* the low hanging fruit.
Did you read the resources about webrtc?

Frankly I didn't want to argue but just point out something I think nobody 
mentioned.
You have to fix Jingle lacking encryption if you want to use OMEMO or any other 
XMPP encryption scheme without leaking data all over the place.
Jingle is difficult to implement as far as many xmpp developers told me.
*And* you have to provide some implementation for many different languages and 
platforms if you want to have more than one client being able to do voice/
video calls. WebRTC provides an SDK for exactly that making implementation in 
all sorts of clients very easy.

But again: I don't want to argue and I won't comment this any more.




Am Freitag, 26. Oktober 2018, 08:02:57 CEST schrieb muppeth:
> And yet barely anyone in last 20years did it. I just want to be pragmatic
> with this. Yes native jingle webrtc would be awesome but since for some
> reason barely anyone did it, why not in the mean time get some low hanging
> fruit with jitsi. Imo i do agree native solution should be the goal, but
> why not have a solution ready here and now for the time being?

**Comment by kitkatloyalist** [comment]
Can not Jitsi be both?

@muppeth @tmolitor-stud-tu

> Whether you want to build your own massively multi-user video conference client, or use ours, all our tools [jitsi] are 100% free, open source, and WebRTC compatible.

https://bloggeek.me/mistakes-developing-webrtc-applications/

I am self educating currently.

**Comment by Echolon** [comment]
@raudy66 https://summerofcode.withgoogle.com/archive/

If you are still interested, maybe you can apply successfully this year?

**Comment by muppeth** [comment]
@tmolitor-stud-tu I am aware that implementing native jingle or any WebRTC is very difficult thing to do. This is the reason why we dont have it present yet. That is why I suggest using jitsi-meet as kind of 'good for now' solution just to have something. 

Matrix is currently using exactly that approach. This would mean that since meet-jitsi is just a webapp, anyone with working web browser could use it. It's not ideal solution but its something. And I think it's not that bad of a solution. For one, you could setup any jitsi instance you want to use (also your own self hosted one). The action of calling/ringing probably is not easy to solve but simple initiating a call with a button (which then basically sends a link to the room as in the linked commit above, makes life easierand we could have straight away something that works everywhere without too much effort. Is it frankeinstein'y? Yes. Is it good enough? Works on Matrix so why shouldnt it work in Xmpp.

**Comment by Echolon** [comment]
FYI https://github.com/dino/dino/issues/154

**Comment by raudy66** [comment]
@Echolon Sry for my late reply. I am currently working on my final thesis and have not enough time. But I am still very interested in this feature.

**Comment by Echolon** [comment]
Fot the record:

https://twitter.com/iNPUTmice/status/1161178897003814913
https://nlnet.nl/project/Conversations/

**Comment by Echolon** [comment]
#435

**Comment by intika** [comment]
I think WebRTC is the easiest way to go here, the framework is already available multi-platform, encryption is already implemented, and there are a bunch of applications that could serve as a base to accomplish this... (one example is talk by nextcloud)... now for a reliable service a STUN + a TURN server would be required (call can work without it but its not reliable)... 
Everything is already there, you can even merge that into a new XMPP standard...

**Comment by intika** [comment]
What about a bounty for the feature ? i think a lot me included would pay to get it done

**Comment by genofire** [comment]
Converstions has no Audio/Video call with version 2.8.0 ...

**Comment by kriztan** [comment]
I'm still working on this. It will come soon.

**Comment by danielreuther** [comment]
Does "working on it" here mean that you are planning on adding value to the implementation and giving back? Or is it that you have been waiting for someone else to implement this while making it appear as if your work contributed in a meaningful way? Just asking 🙂

**Comment by kriztan** [comment]
I've just pushed a beta version with this feature: https://github.com/kriztan/Pix-Art-Messenger/releases/tag/2.4.0.1

**Comment by bennypr0fane** [comment]
I'm running the 2.4.0 release right now and it works perfectly for me with PAM and Blabber.im accounts on both sides. I tried a video call and A/V quality was amazing.

**Comment by bennypr0fane** [comment]
> Converstions has no Audio/Video call with version 2.8.0 ...
Did you mean version 2.4? In any case, all the links in the chain have to support it for the call button to appear in the chat. Indeed I have it with some contacts and some not.

**Comment by kriztan** [comment]
Integrated in version 2.4.0

**Comment by Quix0r** [comment]
I get "connectivity error" messages seen in ejabberd logfile

````
<<"<iq xml:lang='en' to='me@f.haeder.net/Pix-Art Messenger.xxxx' from='other@f.haeder.net/Pix-Art Messenger.a-Qc' type='set' id='yyyyy'><jingle xmlns='urn:xmpp:jingle:1' sid='zyxzyxzyxzyx' action='transport-info'><content name='audio' creator='initiator'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' ufrag='vat5' pwd='9hWPJlXQIpcVtEj2Co24xIIw'><candidate port='35277' foundation='2998251545' component='1' priority='2122260223' type='host' generation='0' protocol='udp' ip='196.98.200.62'/></transport></content></jingle></iq>
...
<<"<iq type=\"set\" id=\"xxxxx\" from=\"other@f.haeder.net/Pix-Art Messenger.xxxx\" to=\"me@f.haeder.net/Pix-Art Messenger.wmGU\"><jingle sid=\"xyzxyzxyzxyz\" action=\"session-terminate\" xmlns=\"urn:xmpp:jingle:1\"><reason><connectivity-error/></reason></jingle></iq>">>
````

**Comment by kriztan** [comment]
@Quix0r Please fill out the issue template and describe how to reproduce the error.

**Comment by Quix0r** [comment]
Okay, better then close this ticket. :-)
