### ISSUE TITLE
Reply on private messages in notification

### ISSUE THREAD

**Issue by kriztan** [kriztan/Pix-Art-Messenger#191]
...should reply in private mode too.

**Comment by zz-ha-dum** [comment]
What is private mode?

**Comment by Echolon** [comment]
@kriztan Are you sure this is a low priority thing?

**Comment by Echolon** [comment]
@zz-ha-dum In group chats MUCs you can send private messages only readable for the selected user. Hold their avatar and select `Send private mesdage`
