### ISSUE TITLE
How to temporarily disable accounts?

### ISSUE THREAD

**Issue by alexolog** [kriztan/Pix-Art-Messenger#195]
Conversations allows temporarily disabling an account via "manage accounts".
I could not find a way to do it in Pix-Art.
If this functionality is missing, please add it.

**Comment by kriztan** [comment]
This function isn't missing, it's a feature.  But there will be an implementation in future releases.

**Comment by alexolog** [comment]
Unfortunately it is important for me so I am back to Conversations Legacy for the time being.
Is there a way to get notified when this becomes available?  I'd like to switch back to Pix-Art as soon as it is.

Thank you.

**Comment by kriztan** [comment]
An exact time frame isn't available at the moment but keep an eye on our support group chat xmpp:support@room.pix-art.de?join
