### ISSUE TITLE
Use IPv6

### ISSUE THREAD

**Issue by genofire** [kriztan/Pix-Art-Messenger#207]
#### General information

* **Version:** 2.0.2
* **Device:** FP2
* **Android Version:** Android 7.1.2 LineageOS 14.1

#### Steps to reproduce
Connect to a dual-stack xmpp hoster.

#### Expected result
Connection with IPv6

#### Actual result

Connected with IPv4

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Pix-Art Messenger and include all the
steps it takes to reproduce the problem.

````
adb -d logcat -v time | FINDSTR Pix-Art > logcat.txt
````

**Comment by reijin90** [comment]
If I may ask, how do you know you are connected via IPv4?

**Comment by kriztan** [comment]
I can't understand your question. Do you have a problem? Questions can be asked in our support chat room support@room.pix-art.de

**Comment by genofire** [comment]
@reijin90 i am the xmpp hoster;)
@kriztan do you mean me? It is saidly Hardcoded in Pix-Art Messenger to use always ipv4, it use ipv6 only if there is no ipv4.

2 Solutions:
- remove ipv4 "prefer" code
- use happy eyeball / [RFC8305](https://tools.ietf.org/html/rfc8305) to detect best connection

**Comment by genofire** [comment]
@reijin90 i am the xmpp hoster;)
@kriztan do you mean me? It is saidly Hardcoded in Pix-Art Messenger to use always ipv4, it use ipv6 only if there is no ipv4.

2 Solutions:
- remove ipv4 "prefer" code
- use happy eyeball / [RFC8305](https://tools.ietf.org/html/rfc8305) to detect best connection

**Comment by genofire** [comment]
Please revert this commit:
https://github.com/kriztan/Pix-Art-Messenger/commit/541b7c3f7fe86d4974cc4d6befe219b22141b16d

**Comment by genofire** [comment]
A happy eyeball implementation would no solution? (with a checkbox "force ipv4" to use the current code)

**Comment by nifker** [comment]
@kriztan Why do you think should 'ipv4 then ipv6' be the default and not vice versa?

**Comment by thereyougo** [comment]
I block ipv6, as does my openvpn tunnel provider. prefer ipv6 no.

**Comment by nifker** [comment]
@thereyougo this is a bad point against the usage of IPv6.
