### ISSUE TITLE
Server down? Certificate is invalid

### ISSUE THREAD

**Issue by Echolon** [kriztan/Pix-Art-Messenger#211]
Hi,
since this night I cannot connect to anything from pix-art.de. It states

_"Error Message_

_Server-toserver connection failed: not-authorized (Your server's certificate is invalid, expired, or not trusted by pix-art.de)"_

I'm using Conversations + mailbox.org, but my friends with Pix-Art cannot send either...

Would be great to fix that quickly! :sos:  :sos:  :sos:  :sos:  :sos: 

Cheers

**Comment by kriztan** [comment]
I can't reproduce this. I'll restart my server today. The certificate is valid, but let me check this.

**Comment by Echolon** [comment]
Thing is, others (so from pix-art.de) couldn't send anything too. Can you send messages to others? _(even outside pix-art.de)_

**Comment by kriztan** [comment]
I've just restarted my server. Please close this if it's working now.

**Comment by Echolon** [comment]
Still haveing this problem. But I checked - pix-art.de to pix-art.de works.

So this is a mailbox.org problem. They can't be serious with how they maintain their server.... :hankey:

**Comment by Echolon** [comment]
Okay, I'm gonna open a ticket at mailbox.org, but can you please ensure that everything is fine from your side or if there are anything due to this server which can be an issue? Because I can still connect with other servers, expect yours.

Kind regards

**Comment by kriztan** [comment]
I am  connected with some other servers so I think everything is fine here. My server logs are warning because mailbox.org is trying to establish an insecure connection.

**Comment by Echolon** [comment]
Hi,
still haveing no connection from Mailbox.org. If you have any logs or so, I could provide to the admins from my server, that would be great. Or just the line which names the insecure connection.

Unfortunately, you and others seem to provide a better service that the paid Mailbox.org administration.... :anger:

**Comment by Echolon** [comment]
?

**Comment by kriztan** [comment]
I've added an exception for mailbox.org because I can't find any errors. Please check if it's working now.
