### ISSUE TITLE
Problems synchronizing via Pidgin w. OMEMO PlugIn and Pix-Art-Messenger

### ISSUE THREAD

**Issue by ProfP30** [kriztan/Pix-Art-Messenger#213]
#### General information

* **Version:** 2.1.0 (beta 2018-07-15) as well as 2.0.2
* **Device:** Xiaomi Redmi Note 4 Global Version
* **Android Version:** XIAOMI.EU MIUI 9.6 v8.4.26
Pidgin (Windows) Version: Pidgin 2.12.0 (libpurple 2.12.0)
OMEMO Plugin Version "lurch": 0.6.7 (https://github.com/gkdr/lurch)
Windows version: Windows 10 version 1803

#### Steps to reproduce

1. Exchange messages in Pix-Art-Messenger with a known contact - OK

2. Launch Pidgin in Windows with "lurch" OMEMO plugin installed, connect to the same account as the receiver of the message
(See https://github.com/gkdr/lurch for details.)

3. In Pidgin you see only a text patterns when receiving messages:

"I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo"

#### Expected result

The message should be displayed encrypted within Pidgin - as in Pix-Art itself and App "Conversations".

Note: The message will be displayed correctly in App "Conversations". 
Also when writing from Conversations, the message will be decrypted and shown correctly in Pidgin (and Pix-Art-Messenger).
So, with Conversation the sync (encrpyting/decrpyting) works, problems occurs only in Pix-Art-Messenger.

#### Actual result

From Pix-Art to Pidgin: Only the text pattern is being displayed.
From Pidgin to Pix-Art: Nothing is being displayed at all.

Conversations: everything works, back and forth.

#### Debug output
./. (missing)

**Comment by kriztan** [comment]
I think you have to validate/trust your own keys within all messengers. Within Pix-Art Messenger have a look into your profile and look for your omemo keys. 
Pix-Art Messenger doesn't behave different than Conversations so it is a client/user based problem. Please join our support chat group for detailed discussions.

**Comment by ProfP30** [comment]
Issue solved by re-installing Pix-Art Messenger.
Most likely issue occured because previously a backup was restored.
With simply re-installing, now without restoring the backup, everything seems to work.

**Comment by ProfP30** [comment]
Discovered several problem with Pidgin/Windows v2.12.0 (libpurple 2.12.0) and OMEMO Plugin Version "lurch": 0.6.7 

They don't appear in Gajim/Windows v1.0.3.

Strongly recommend to use Gajim for OMEMO-Jabber Conversations/Pix-Art Messenger.
