### ISSUE TITLE
what is the benefit of pixart over conversations?

### ISSUE THREAD

**Issue by ramack** [kriztan/Pix-Art-Messenger#215]
#### General information

I have just Seen pixart on f-droid and from the description i Wonder what you changes compared to the source conversations. Repeating the features of conversations in the description mit be not so import an than explicitly highlighting what is different. And for sure you should add Screenshots to back up the improvements.

**Comment by Echolon** [comment]
--> https://freie-messenger.de/sys_xmpp/conversations/ --> Unterschiede Conversations/PixArt 

Unfortunatly in German, maybe Google helps. Maybe outdated, too.

**Comment by ramack** [comment]
Doesn't look revolutionary... did you consider sending pull requests to conversations instead of forking?

**Comment by kriztan** [comment]
Yes, some years ago...
I'm closing this now. We can talk about this inside our support group chat.
