### ISSUE TITLE
Tag betas

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#217]
Since F-Droid can autoupdate builds, if you don't differentiate unstable (alpha/beta) from stable it will pull the latest unstable and [promote it as stable and recommended](https://gitlab.com/fdroid/fdroiddata/commit/f2a7fff53256c56debd0dcae13120c2d2d49733d).

Hence given the current `UpdateCheckMode: Tags ^[0-9.]+$`, could you re-tag (or in the future tag) betas with `2.1.0-somestring` as opposed to stable tags like `2.1.0` ?

**Comment by genofire** [comment]
@licaon-kter you know it maybe better then me.
Who is it possible to detect new updates, without setting the `CurrentVersion` up to the new "beta" update?

I think the commit tags of @kristan are now well `2.1.1.1-beta` for a beta and a numeric one for stable like `2.1.0`. We just need F-Droid to understand it this way. (or i am wrong)

**Comment by licaon-kter** [comment]
It already understands it.

**Comment by genofire** [comment]
Is there a possibility to detect new version with setting them up to `CurrentVersion`.
I really like to try the betas over the f-droid. (on f-droid client there is a option to use `Unstable Version`.

**Comment by licaon-kter** [comment]
@kriztan Please Tag unstable as X.X.X.X and stable as X.X.X as discussed.

Ref: https://gitlab.com/fdroid/fdroiddata/-/blob/9e86ad103dede8a15ee6b2777c2c78b31d17be34/metadata/de.pixart.messenger.yml

Because: https://github.com/kriztan/Pix-Art-Messenger/releases/tag/2.3.5

**Comment by kriztan** [comment]
sorry, my mistake.
