### ISSUE TITLE
Updater should use Tor if enabled

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#219]
#### General information

* **Version:** 2.1.0 (beta 2018-07-15)

#### Steps to reproduce

1. Enable Tor
2. Check for Updates

#### Expected result

Updates are found or not...

#### Actual result

Error connecting, because the app tries to contact the server via clearnet and that is blocked.

**Comment by kriztan** [comment]
It will be available in upcomming version 2.1.0.

**Comment by kriztan** [comment]
Should work with ef6dc57d5a3d01cb3a79123efc63803f7067ff8b now
