### ISSUE TITLE
How do you disconnect from the server?

### ISSUE THREAD

**Issue by hasufell** [kriztan/Pix-Art-Messenger#222]
In conversations it used to be very easy to disconnect. I have no idea how to do this in Pix-Art Messenger, except hard-killing the app.

So either this feature is missing or it is buried in a way that makes usability hard.

**Comment by kriztan** [comment]
An offline mode is not available as default. But you can enable multi account mode in expert settings and then you can easily de-/activate your account(s).

**Comment by hasufell** [comment]
> An offline mode is not available as default.

Why not? I would say that is a basic requirement for usability.

**Comment by kriztan** [comment]
For normal users it's not important to go offline and it is no feature to improve usability. If you don't want to get any messages switch your device into flight mode.

**Comment by hasufell** [comment]
> If you don't want to get any messages switch your device into flight mode.

You mean disabling specific application notifications, because I'm currently chatting via my laptop, is not a common use case and I should disable my whole phone? :roll_eyes:
