### ISSUE TITLE
Translate Readme to English

### ISSUE THREAD

**Issue by Nutomic** [kriztan/Pix-Art-Messenger#228]
I think the readme should be translated to English, to make it more accessible for people who don't speak German. The same goes for the website.

If you are interested, I could do this translation and make a PR. I would also remove the whole section about ADB logs and just link to stackoverflow or some other site that has a good description.

What do you think?

**Comment by kriztan** [comment]
Hi, sorry for my late response.  You may copy the ADB part to the github wiki. And yes, you can start translating :) thanks

**Comment by TheOneric** [comment]
As a translation is now available, I believe it would be ok to close this issue.

**Comment by kriztan** [comment]
added via 6a8fb3e8aed08df03198b5909964fb91a5e78f39
