### ISSUE TITLE
Document on F-Droid+GooglePlay this is a single-account client only

### ISSUE THREAD

**Issue by jankratochvil** [kriztan/Pix-Art-Messenger#229]
#### General information

* **Version:** 2.1.0
* **Device:** Motorola Droid 4
* **Android Version:** lineage-14.1-20180810-nightly-maserati-signed.zip

#### Steps to reproduce

Install application is an improvement of Conversations.
Try to add 2 accounts.

#### Expected result

Two XMPP accounts active.

#### Actual result

I haven't found how to add a second account.

**Comment by kriztan** [comment]
There is no need to do this because this isn't a single account app. Have a look into the expert settings to activate multi account mode.
