### ISSUE TITLE
KiND QUESTiON: looking for option to specify own resource

### ISSUE THREAD

**Issue by github-tomster** [kriztan/Pix-Art-Messenger#231]
if a file is sent to an contact, with two identical devicetypes (phone) one in a car an one in the pocket,
how can the sender distinguish between car-phone and pocket-phone?
is there a way to edit the resource Pix-Art Messenger.OWH7 ?

**Comment by kriztan** [comment]
If you have a well configured server, you don't need to know that, because all devices will get the files. So there is no need to rename the resources.

**Comment by kriztan** [comment]
Have a look at https://compliance.conversations.im/
File transfers should be handled with httpupload and your provider should support carbon copies.

**Comment by github-tomster** [comment]
thats it!
XEP-0280 is available
XEP-0363 is not...
thank you!
