### ISSUE TITLE
very kudos

### ISSUE THREAD

**Issue by brighterness** [kriztan/Pix-Art-Messenger#232]
This is an improvement to Conversations.  I truly **appreciate** you selection of app default enabled functionality: Socially Sharing Myself.

I detest the defaults of Conversations and the cretinous labeling thereof which almost always ENCOURAGES people to disable them, or actively discourage them from enabling them when they configure the app themselves

#deleteSMS

**Comment by zz-ha-dum** [comment]
> #deleteSMS

📣 amen!!
