### ISSUE TITLE
integrate Giphy

### ISSUE THREAD

**Issue by geronimoge** [kriztan/Pix-Art-Messenger#236]
It would be great to see giphy integrated.

More informations: 
https://developers.giphy.com/docs/
and
https://signal.org/blog/giphy-experiment/

**Comment by Echolon** [comment]
Hey, yes would be great.

But it's already a double. Please close.

@geronimoge please vote up here: #170

**Comment by zz-ha-dum** [comment]
i would prefer a plugin.  I don't want to be drown in MeMes by *those* people

like the bygone plugins used for share location or record audio snippet

**Comment by MalevolentGrin** [comment]
If this is added I would like an option to not-show animation in GIF (unless clicked)
