### ISSUE TITLE
suggestion:  MUC for suggestions and questions

### ISSUE THREAD

**Issue by unicorntaco** [kriztan/Pix-Art-Messenger#239]
Conversations github [sometimes eventually] encourages people visit their MUC [and sometimes informs users the address] for suggestions and usage questions.  Does Pix-Art have similar?

**Comment by kriztan** [comment]
Have a look into the readme, there you will find a link to join our support group chat:  [support@room.pix-art.de](https://jabber.pix-art.de/j/support@room.pix-art.de?join)
