### ISSUE TITLE
FR: Option to change database password

### ISSUE THREAD

**Issue by 7usr7local** [kriztan/Pix-Art-Messenger#243]
If you enable Multi-Account mode, you are requested to enter a password for the combined backup database. 

However, when enabling Multi-Account mode, one has in mind to get into contact with people, maybe quickly. - not making up new good and rememberable passwords.

This leads either to simple passwords you'd like to change later or to passwords you are going to forget.

For both cases it would be nice to set a new password afterwards (overriding the old one) which then will be used with the next backup so all future backups are encrypted with the new one.

NB: For usecase 2, I recommend not to ask for the old password. It won't make sense anyway as somebody having access to your configuration can as well create an unencrypted text-export without fiddeling with your encryption settings.

**Comment by kriztan** [comment]
Thanks for your message.
Please have a look at my thoughts.

A password should not be so simple, but this is the risk of the password creator.
A resettable password without asking for the old one is the same than saving all the data in plaintext. A thief could for example set a new password to import your data including all encryption keys and this is a high security issue. So I decided to forbid changing the password at later time. The only way will (in future) be to delete all except one account to disable multi account mode and reset the saved password. In this case the account password is used for upcoming backups.
Keep in mind, that the backup not only saves the messages, but also all en-/decryption keys for all your devices and contacts.

**Comment by peterjw** [comment]
Hi kriztan,

thanks for your answer.

> A password should not be so simple, but this is the risk of the password creator.

Right. And it would by nice by the programmer to give the password creator a chance to do better if he chose a bad one in the first go. :wink:

> A resettable password without asking for the old one is the same than saving all the data in plaintext.

No, not the same. Encrypting data is basically useless as long as you have access to the unencrypted data (e.g. your chat history in the running messenger) on the same place. And I would consider the file system of your Android where you messenger runs on the "same place" as the messenger.
As soon as you have an off-site backup of your phones file system or copy it to your new phone or any other scenario of transport, it makes much of a difference. And in this case, resetting the password on the source (the messenger) for comming backups does not void the security of the allready encrypted database at the other place.

Having said that, I see your point regarding the access to the communication encryption keys. (Further thoughts on that below)

Still I would like to keep up my feature request for use case 1 as I believe, giving a trivial password at the first prompt and changing it later to a better one is a common usage pattern, but I might drop my wish to do this without entering the old one :wink: 

However, your scenario is an unauthorized user having access to the unprotected running app. This is allready a security breach by itself and implies many more security issues. Other apps prompt for an encryption passwort at the time of backup, not at the time of apps first time setup.

BTW: How does this work in the single-account mode if the user changes the account password?

Regarding your future plans: How reasonable is it to allow resetting the password after deleting all but one accounts while you thoroughly try to inhibit it in the other case?

**Comment by kriztan** [comment]
Not valid anymore because backup password is account password
