### ISSUE TITLE
[enhancement] Add options for the integrated update service

### ISSUE THREAD

**Issue by kai1703** [kriztan/Pix-Art-Messenger#258]
I would prefer to add a option to configure the integrated update service.

My problem is the prompt, to enable unknown resources, in the Android settings, permanently.
Because Android gives the ability, to give a temporary permission for every installation (or it's just included in Samsung devices).

In this prompt, I would add a second button like: *I know, continue and don't ask again*.
Or add a link to the settings, where you can choose between:
* Update automatically
* Download updates and ask for installation in a notification
* Notify about updates
* Disable update service

Some people who are not technically experienced could also be shocked about this prompt, I mentioned before. Because the Android system notes that, enabling unknown sources could be a security issue.
So I would enable only notifications about updates by default.

**Comment by thereyougo** [comment]
> that, enabling unknown sources could be a security issue

yeah right.  (sarcasm)

They should stop promoting malware apps first: every. single. app rendering 3rd party web ads == malware.

**Comment by kriztan** [comment]
added via 721bbf47774f452ec8a87a56f1042b555022efba
