### ISSUE TITLE
Add ability to switch offline

### ISSUE THREAD

**Issue by BaumGuard** [kriztan/Pix-Art-Messenger#274]
In Conversations you can switch offline easily when you go to "Manage Accounts" and put the slider to the left. In Pix-Art Messenger I haven't seen an option to switch offline yet. So it would be nice, if that could be implemented.

**Comment by kriztan** [comment]
This feature is not necessary for an instant messenger.
But you can select multi account mode and you will see the manage accounts screen where you can use the sliders to go on and offline.

**Comment by bleedingcrow** [comment]
@kriztan 

This is the slippery slope you open by entertaining 

https://github.com/kriztan/Pix-Art-Messenger/issues/377

The slow crippling of utility through misplaced distrust
