### ISSUE TITLE
FR: Preserve attachment file name

### ISSUE THREAD

**Issue by 321freddy** [kriztan/Pix-Art-Messenger#275]
It would be nice if the App could preserve file names of recieved and sent files.

Currently all files (either recieved or sent) get a new automatically generated name.
I tested this with a server that preserves the original file names for HTTP uploads via XMPP.

If the file with the given name already exists the App could fallback to an auto-generated name.

Thanks in advance!

**Comment by kriztan** [comment]
Which advantages do you expect if file transfers keep their original file names?

**Comment by kriztan** [comment]
I think you are the only one with this kind of problems concerning the original file names. I've looked into the source code, each client seems to do his own thing. Some clients are using original filenames, some changes them. So a change on the receiving site won't help you if the sender changes the name during fileupload and vice versa. I won't change this at the moment. 
I'll add the `tgz` files to the known files within the messenger.
