### ISSUE TITLE
Option to save files encrypted on local storage

### ISSUE THREAD

**Issue by Perelandra0x309** [kriztan/Pix-Art-Messenger#278]
#### General information

* **Version:** 2.1.4
* **Device:** Motorola G4 Play
* **Android Version:** Stock Android 7.1.1 

#### Steps to reproduce

1. Send or receive a photo or file in a chat
2. Use a file explorer app and go to /your_storage/Pix-Art Messenger/Media to see files unencrypted

#### Request

Could there be an option to save these files in the encrypted database instead of public storage where all other applications have access to them?  Even if the files are sent with OMEMO encryption they are decrypted upon delivery and stored so that they appear even in your Photos app.  I happen to also have an app setup to automatically backup all images in Photos to the cloud (helps me manage photos taken with several devices in one central location) and so images sent in xmpp chats get mixed into my other photo shoots.  Conversations has the same issue, so adding this feature would make Pix-Art more secure and differentiate it.

**Comment by kriztan** [comment]
I think this is very complicated, because a lot of files will make a database grow up very fast. Every read and write access will lock down the database and this will reduce the user experience. Image and video previews will be generated slower and each file access will slower too. So If you want to hide the files from other apps, you could add a `.nomedia` file which will not prevent other apps to see the files, but most apps respect that and won't show them in the gallery apps.
If there any other thoughts about this, feel free to add your ideas in this issue.

**Comment by Perelandra0x309** [comment]
Thanks for the reply. Yes the size of the database may get large and that is something for the user to manage. Whether files are stored in the database or on the file system wont be much of a difference in actual drive space used.
My concern is not for apps that "play nice" but those that may ignore pleasant requests for privacy and just scoop up anything they can. A phone can now have just as much data as a personal computer. Also an encrypted database would help defend against deliberate copying of device data at border crossings by overly zealous agents who may or may not be acting under correct application of law.
Encrypted messengers rightly tout the importance of end to end encryption, but endpoint security is just as important.

**Comment by kriztan** [comment]
Surely you are right about the endpoint security, but I do not think that this is the task of the messenger. If you have such secret data on your device, in my opinion you should save them in the right way. New Android devices are supporting full disk encryption, which will prevent foreign accesses or at least make a lot of work to decrypt the data to access them. And furthermore you should be carefull which app you install on your device. I'm not developing an app which is used for secret services or government officers. So I think this will overshoot the mark. I'm closing this now.
