### ISSUE TITLE
Tracking via Google's FCM

### ISSUE THREAD

**Issue by mq58nzk4uxz** [kriztan/Pix-Art-Messenger#281]
#### General information

Version: 2.1.4 - Play Store
Device:
Android Version:

#### Issue

According to [this report](https://reports.exodus-privacy.eu.org/en/reports/45027/) Pix-Art contains a tracker.

When you add Google's FCM / Firebase Cloud Messaging (which you did, according to the changelog - version 2.1.1: "add push messages for playstore versions"), tracking is activated by default - i. e. sending analytics data to Google's app-measurement.com. As a developer you have to add code to deactivate the tracking. This can be done by adding
`<meta-data android:name="firebase_analytics_collection_deactivated" android:value="true" />`
to the android manifest file.

I reckon you, too, don't want this tracking to be happening via your app so I hope you can add this little fix as soon as possible.

Also, have a quick read on [this article](https://www.kuketz-blog.de/vorsicht-android-entwickler-beim-umstieg-von-gcm-auf-fcm-ist-tracking-aktiviert/) for clarification.

**Comment by kriztan** [comment]
Thanks, I'll add the line to the manifest and remove the unwanted tracking.

**Comment by kriztan** [comment]
I've looked into the code, and this is already set: https://github.com/kriztan/Pix-Art-Messenger/blob/master/src/standardPush/AndroidManifest.xml#L8

Do you have any other ideas?

**Comment by mq58nzk4uxz** [comment]
Let's just assume, the Exodus report is inaccurate then.
