### ISSUE TITLE
[feature request] change nickname/edit profile within pix-art

### ISSUE THREAD

**Issue by benjaminbischoff** [kriztan/Pix-Art-Messenger#282]
It would be great to have the option to change the for others displayed nickname directly within pix-art.
Otherwise atm it is only possible to install Gajim to do that.

**Comment by kriztan** [comment]
This is a nice idea.

**Comment by kriztan** [comment]
implemented with 4e78a72af907ac32eccd87ebdbf6ec44a4336d36
