### ISSUE TITLE
Close chat when deleting full history

### ISSUE THREAD

**Issue by mzmitrulevicius** [kriztan/Pix-Art-Messenger#289]
Would it be possible to close chat, when history is cleared automatticaly?

**Comment by kriztan** [comment]
For single chats you can check the checkbox and the chat is closed after clearing history. For group chats the checkbox doesn't exist because closing means that you leave the group and no longer receive any messages.

**Comment by mzmitrulevicius** [comment]
Yes if i do clear history, and check box it close chat, but if there is auto deletion chat doesn't close.
Maybe is it possbile to close chat when auto delete is made and chat is empty

**Comment by Bondarz** [comment]
can i use this thread? ;)

Self-destruction of a **single chat** after a fixed time, for example 10 minutes.

In the settings i only detected "delete all messages" after one day or 12 months.

**Comment by kriztan** [comment]
I suspect that some users would find it strange if suddenly less or no chats are available (after automatic message deletion). It should remain as it is.
