### ISSUE TITLE
There is no way to close the app

### ISSUE THREAD

**Issue by readyblue** [kriztan/Pix-Art-Messenger#290]
#### General information

* **Version:** eg 2.1.5
* **Android Version:** Android 7.1.2  LineageOS

#### Steps to reproduce

I am done using this app, I want to close it, to quit using it.

#### Expected result

closing app on back button, if no other option to close,exit, or quit it is in the menu somewhere

#### Actual result

back button just place this app to the background, still running

**Comment by kriztan** [comment]
This is the expected behavior. Shutting down the app will result in not getting any messages and this is not intended.

**Comment by OmlineEditor** [comment]
I want to close the app and I don't need to receive messages. please add a full close button.

**Comment by kriztan** [comment]
What you want is not everybodys wish.
