### ISSUE TITLE
Pidgin user show as offline, even when it is in fact online, delivery reports confirms it

### ISSUE THREAD

**Issue by readyblue** [kriztan/Pix-Art-Messenger#292]
#### General information

* **Version:** eg 2.1.5
* **Android Version:** eg Android 7.1.2 LineageOS

#### Tested environment
client A: Pix-Art 2.1.5
client B: Pidgin 2.10.12 (libpurple 2.10.12)

Client A does not see online client B even when it is in fact online.
Message delivery reports is working both directions.

**Comment by kriztan** [comment]
Thanks for your report, but I think this is not a bug. In many cases the remote user didn't share it's online status.
In Pix-Art Messenger you can configure this within the contact details. But I don't know where to do that for pidgin.
