### ISSUE TITLE
Import doesn't accepts jabber-password

### ISSUE THREAD

**Issue by BaumGuard** [kriztan/Pix-Art-Messenger#294]
I made a backup of the Pix-Art Messenger to import it to my new phone. As I wanted to do that it asked for my password and I typed in my jabber-password but it hadn't been accepted. I tried it several times but it didn't work. I'm sure I've typed in the corect password because it works when I configure my account in Pix-Art.

**Comment by kriztan** [comment]
Please let me know which messenger versions and android versions you are using on the backup and import side. Do you use multi accounts? Do you have root access on the backup side?

**Comment by BaumGuard** [comment]
I have only one account. On the mobile phone on which I export the database has Android 8.1 and the one on which I want to import the database has at the moment Android 7.1.1 but there's running an update at the moment.

**Comment by kriztan** [comment]
Please use the same messenger versions for backup and import.

**Comment by kriztan** [comment]
Should be fix in upcoming version 2.2.0
