### ISSUE TITLE
[UX]: Stop password generation per default

### ISSUE THREAD

**Issue by Echolon** [kriztan/Pix-Art-Messenger#296]
Hi,

this is about people forgetting their password. Or being more precise: Never knew their password at all.

I agree, that Pix-Art makes on-boarding very easy by just letting the software generate a password. But the experience lags once people try to login in from somewhere else or again another day. And even if they try to find support, they are kinda stucked in an dead-end again (see also #295).

Thus I like to suggest to stop automatically generate passwords at all or at least make it only possible by an action from the user (e.g. show a button).

Cheers

**Comment by WhenNotMe** [comment]
and/or a visible link to a wiki explaining how to backup this password especially when not using GoogleServices.

**Comment by Echolon** [comment]
No, sorry, I rather disagree. Users should be do this step. I think I would better to focus on other improvements about onboarding.

**Comment by kriztan** [comment]
With 77d327c0cebedc09ab7264ee33570f6a33d0a8a7 the created password will be shown in a dialog. I think this fixes this although it's not exactly what you have requested.

**Comment by Echolon** [comment]
Actually, I would like to reopen.

The auto-gen password should be the default way. The only thing I suggest to implement is as opt-in option. Something like "Generate a password".

This will comeback once the people get a new device or so :(

**Comment by kriztan** [comment]
What is wrong with the current implementation?

**Comment by Echolon** [comment]
People still get "directed" to just create an auto-generated passwort. This is a problem as they:

- likely never see the password
- and if so, likely cannot remind it

This automatically creates a user base which is forced to apply for a new password in the future or create another new account, which I think is not the idea. Also this frustrates and furthermore they don't understand how to get the password reset or so.

I think the problem with onboarding to xmpp is never the password step. Most friends dropped it because push doesn't work properly.

**Comment by virtadpt** [comment]
This.  I've been trying to get some of my friends onto XMPP with P-A-M, and this has been a huge stumbling block.  Most of them have given up (in part because they haven't realized that I can reset their passwords on my server) because the UX makes it look unreliable.

**Comment by kriztan** [comment]
Sorry @Echolon and @virtadpt this is personal incompetence. The password is shown in a dialog after it is created with the possibility to copy is via button into the clipboard to save it anywhere.

**Comment by kriztan** [comment]
I've just created some screenshots and can't understand why a user is not able to realize the password:
![Screenshot_20190621-202740_Pix-Art_Messenger](https://user-images.githubusercontent.com/3350754/59943806-7c530700-9463-11e9-9760-74906b14d372.png)
![Screenshot_20190621-202749_Pix-Art_Messenger](https://user-images.githubusercontent.com/3350754/59943810-807f2480-9463-11e9-9cc7-40054a56ad89.png)
![Screenshot_20190621-202810_Pix-Art_Messenger](https://user-images.githubusercontent.com/3350754/59943814-8248e800-9463-11e9-8047-41e0065bc27f.png)
![Screenshot_20190621-202818_Pix-Art_Messenger](https://user-images.githubusercontent.com/3350754/59943818-85dc6f00-9463-11e9-81f4-e943999f8a97.png)
![Screenshot_20190621-202821_Pix-Art_Messenger](https://user-images.githubusercontent.com/3350754/59943821-88d75f80-9463-11e9-8d69-f34aceb91787.png)

**Comment by Echolon** [comment]
@kriztan Hi, I think its not about incompetence (okay, maybe it is). But I guess we try to overcome the cosmic distances from us to the "normal" users. I rather think its just the case of not caring and also not story passwords anywhere.

Lets treat it from this side:

- People don't like passwords and registration. I think that's what we all agree on
- Still, registration and using a password is a common thing.
- Thus, people are used to creating accounts and thinking about what password to take.

I still suggest: Just let them do it. On the long-run we achieve more than we might loose by asking them to set a password.

- You still can offer a button which will do the automatic password generation and also offer them to copy it. This would only change the "hierarchy". And I am convinced (by many experiences) it will be fine.

PS: Just on Wednesday I ask a friend to install Pix. I was watching the steps with him. When it came to the password, I suggested him to set his own password - and he just did it, no discussion or problems.

**Comment by kriztan** [comment]
Okay, maybe it is sufficient to add a hint in the dialog to set your own password on the next screen?

**Comment by Echolon** [comment]
I don't fully understand your suggestion. Can you precise?

**Comment by kriztan** [comment]
I mean it this way:
![Screenshot_20190622-171739_Pix-Art_Messenger](https://user-images.githubusercontent.com/3350754/59965701-f346d900-9511-11e9-9b76-fd4dbb335e49.png)
