### ISSUE TITLE
Can the map preview be clarified

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#304]
...it runs on your server, but I don't see any info in the Privacy Policy.

What do you log exactly? Longitude? Latitude? Where do the maps come from?

**Comment by kriztan** [comment]
How the preview image is generated can be seen in this line https://github.com/kriztan/Pix-Art-Messenger/blob/master/src/main/java/de/pixart/messenger/utils/GeoHelper.java#L45

The apache is storing this with an anonymised IP:
XX.XX.XX.0 - - [18/Feb/2019:18:25:55 +0100] "GET /staticmap/staticmap.php?center=49.321025,29.1249844&size=500x500&markers=49.321025,29.1249844&zoom=15 HTTP/1.1" 200 356913 "-" "okhttp/3.10.0"

The server is loading OSM map tiles.

The original script can be found here: https://github.com/kriztan/staticmap

**Comment by licaon-kter** [comment]
So we'll have to add `AntiFeature: Tracking` to F-Droid since you log GPS coords of users of your app?

**Comment by licaon-kter** [comment]
FYI, by default F-Droid doesn't list apps with anti-features, one needs to toggle it ON in settings

Ref: https://gitlab.com/fdroid/fdroiddata/commit/9559d59dcefd7d2fc3e7c3845cb1d401aab755c8

**Comment by kriztan** [comment]
It's not very helpful to blame the app with your hint on fdroid. The kind of "tracking", as you call this, is no tracking because the IP is not completely stored. And I'm not a profit organization which makes money with this logs. It would be better to contribute a secure solution instead.

**Comment by licaon-kter** [comment]
Right, it would. Hope somebody that can code actually does. I'm not blaming anything, just pointing out so users don't have surprises.

One mention, the metadata uses the description from your repo. I wanted to add a note to it explaining why the antifeature tag is there.

Are you open to a PR?

**Comment by kriztan** [comment]
Thanks, yes I'm open to a PR.

**Comment by Bubu** [comment]
> FYI, by default F-Droid doesn't list apps with anti-features, users need to toggle it ON in settings

I'm pretty sure it does. (there's a toggle that would imply otherwise in the settings but that was never working.)

**Comment by licaon-kter** [comment]
@Bubu I was thinking about that, never bothered testing so I though it works :))

**Comment by l-jonas** [comment]
Why not use something like <https://github.com/osmdroid/osmdroid>? Then the data does not come from your server and the client only sends which tiles he needs (and not the exact location). Moreover, this would allow moving the map.

**Comment by kriztan** [comment]
@l-jonas we are discussing about the preview image inside the chat, not the map integration at all. So your suggestion doesn't help at this point. 

But I want to clarify why I'm using the current integration: 
The osm map tiles are relatively big image files (tiles) which are not good for regions with bad connection speeds. Depending on the location it's necessary to download one or more of this tiles. So a small preview generation on the mobile could download multiple megabytes and would take, depending on your connection speed, some minutes... So I've decided to let my server generate this small preview image, this uses only few kilobytes (e.g. 10 kib) and takes only some seconds.
