### ISSUE TITLE
Fix versionName and code

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#307]
You've tagged `2.2.0.1-beta` as **2.2.0 beta (2019-02-09)** code **251**

Then `2.2.0` but kept **2.2.0 beta (2019-02-09)** code **251** so it's stable or not?

Then `2.2.0.2-beta` as **2.2.0 beta (2019-02-10)** code **252** which is newer than stable?

**Comment by genofire** [comment]
Oh okay, i have not seen the tag `2.2.0` -> just the github releases.
I believe this tag should not be pushed by @kriztan .

**Comment by genofire** [comment]
i will create a F-Droid merge request if this tag is deleted to revert the wrong declered Stabil version

**Comment by genofire** [comment]
Tag deleted - issue could be closed now

**Comment by genofire** [comment]
Dammit - again - https://gitlab.com/fdroid/fdroiddata/commit/04801c0f38cf851c03db4af3c24e043edbb30739

Cache on F-Droids Build server?

**Comment by licaon-kter** [comment]
No, the `Tags ...` needs to be modified... Will do later

**Comment by kriztan** [comment]
Don't modify the tags because it will break the internal updater. The beta tags should have 4 digits instead of the final ones with only 3 digits.

**Comment by licaon-kter** [comment]
@kriztan Right...
https://gitlab.com/fdroid/fdroiddata/commit/5bc8d68c7147bb04e1f9d8ec4255415ff25f3896

**Comment by kriztan** [comment]
Thanks @licaon-kter

**Comment by licaon-kter** [comment]
So this is cancelled?
https://github.com/kriztan/Pix-Art-Messenger/commit/598e61996583ded79ec795945c91ee4d89faca6f

**Comment by kriztan** [comment]
I can't understand the problem... @licaon-kter

**Comment by licaon-kter** [comment]
```
INFO: Successfully built version 2.3.7 of de.pixart.messenger ERROR: Could not build app de.pixart.messenger: Unexpected version/version code in output; APK: '2.3.7beta_(2020-04-01)' / '299', Expected: '2.3.7' / '299' 
```

**Comment by kriztan** [comment]
I've retagged the version 2.3.7 --> should be fixed with https://github.com/kriztan/Pix-Art-Messenger/releases/tag/2.3.7
