### ISSUE TITLE
mp4 video: no preview

### ISSUE THREAD

**Issue by meaz** [kriztan/Pix-Art-Messenger#312]
#### General information

* **Version:** 2.1.5
* **Device:** Samsung Galaxy S4 mini
* **Android Version:** LineageOS 15.1

#### Steps to reproduce

Open a muc

#### Expected result

See the video preview of videos sent by participants

#### Actual result

Videos preview are not visible: instead, the participants messages contain the url to the videos, for example `https://myserver/upload/video.mp4`.
If I open the same MUC with Conversations, I do see the video preview.

**Comment by kriztan** [comment]
Related to #311
