### ISSUE TITLE
application lock

### ISSUE THREAD

**Issue by free-14** [kriztan/Pix-Art-Messenger#313]
#### General information

* **Version:** eg 1.20.1
* **Device:** eg Google Pixel
* **Android Version:** eg Android 7.1.2 Stock or Android 6.0.1 LineageOS

#### Steps to reproduce

1. Tell me, are you considering the option of blocking the application?
2. A lot of people need additional application blocking. Android (default) does not have a built-in application for blocking local applications.

**Comment by kriztan** [comment]
I think this isn't necessary on app level  because you can, or even better should lock your device at all instead of only one app.

**Comment by free-14** [comment]
I agree. I have full phone encryption + lock at the entrance. BUT. Sometimes there is a situation when you give people a phone to call or send SMS or browser. And at this moment applications become vulnerable.

**Comment by kriztan** [comment]
Don't do this and use Android's guest mode for this.

**Comment by free-14** [comment]
There is no such function in my phone. kyocera torque G02

**Comment by kriztan** [comment]
Then don't give your device out of your hands.

**Comment by free-14** [comment]
)))). I understand that you do not want to do this. It's easier for you to edit already ready Daniel code. But you can tell or direct how I can implement this in your application.?
