### ISSUE TITLE
[UX] Fully show error message in the failed message

### ISSUE THREAD

**Issue by Echolon** [kriztan/Pix-Art-Messenger#314]
Hi,

I would like to suggest to put the actuall error message below in the failed message.

XMPP is decentral, so I think it is important to do some extra efforts in consistency for the users. Especially users who even don't know that there is a possible error message. Yes, it would be great to know the error and improve about this, but not all errors are app related and its 'ultra' hard to get some valid information out of non-savy users.... so this could be a good step to get some information and dont let the user alone with the problem, which is no solution at all in my opinion. I think this would be good thing about experience wihtin the app and the network in general.

Here, a crappy visualised suggestion:

<img src="https://user-images.githubusercontent.com/29168011/52878840-eed27400-315d-11e9-8d49-8621201b1aad.png" width="250">

Kind regards & thanks for the app development

FYI: Also posted here: https://github.com/siacs/Conversations/issues/3379

**Comment by kriztan** [comment]
Fixed via a5019812fbdaf57096b8483778b610fd3b0d1887
The error messages are in many cases very short and not understandable for normal users, so it's best to not show everything. The error message can be shown, copied and sent via long press.
