### ISSUE TITLE
Option to disable backup

### ISSUE THREAD

**Issue by abidal3** [kriztan/Pix-Art-Messenger#322]
Please add options to disable backup creation and to change backup path.

**Comment by kriztan** [comment]
This is not possible because the app needs a specified path to look for a backup.

**Comment by kriztan** [comment]
Disabling the backup is not recommended. Do you have a reason why it should be disabled?

**Comment by abidal3** [comment]
> This is not possible because the app needs a specified path to look for a backup.

Please explain why exactly the app needs this path.
If you can't do without it then maybe add option to create backup in /data/data/de.pixart.messenger subdirectory or sdcard.
For example so done for cache in Total Commander.

**Comment by kriztan** [comment]
In the case of restoring a backup the app needs a path to look for a possible backup. If you divine your own path somewhere else, the restore process can't know it. Why should the location be changed?

**Comment by kriztan** [comment]
What's wrong with the current implementation?

**Comment by abidal3** [comment]
> Do you have a reason why it should be disabled?

For security reasons.
Sdcard path is public for all apps.

**Comment by kriztan** [comment]
What's the security problem?

**Comment by abidal3** [comment]
All apps can read this backup.
Even in Total Commander made ability to save cache in /data/data/com.ghisler.android.TotalCommander or sdcard for security reasons.

**Comment by abidal3** [comment]
Would you reopen the issue for public discussion?

**Comment by kriztan** [comment]
There is no security issue because the backup is encrypted

**Comment by abidal3** [comment]
That's fine!
What cryptoalgorithm is used?
Can be also encrypt backup file name?

**Comment by kriztan** [comment]
AES, the Name could not be encrypted

**Comment by abidal3** [comment]
> AES

How long is the key?

> the Name could not be encrypted

Why?

**Comment by kriztan** [comment]
Have a look into the code.
