### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by abidal3** [kriztan/Pix-Art-Messenger#323]
> This is not possible because the app needs a specified path to look for a backup.

Please explain why exactly the app needs this path.
If you can't do without it then maybe add option to create backup in /data/data/de.pixart.messenger subdirectory or sdcard.
For example so done for cache in Total Commander.

**Comment by kriztan** [comment]
Don't create multiple issues with same questions!

**Comment by kriztan** [comment]
Duplicate of #322

**Comment by abidal3** [comment]
> Don't create multiple issues with same questions!

Sorry.

**Comment by abidal3** [comment]
You said
> Don't create multiple issues with same questions!
But you close issues as quickly as possible.
Why?
I'm a simple user. I can't formulate my thoughts quickly.
Please not close issues quickly.
I would like to discuss some points.

**Comment by abidal3** [comment]
> This is not possible because the app needs a specified path to look for a backup.

But I manually delete these backup files from Database directory and Pix-Art continues to work well.
Why this isn't possible?

**Comment by kriztan** [comment]
You can join my support group

**Comment by abidal3** [comment]
> You can join my support group

support@room.pix-art.de ?
But just since we started discussing here we could end the discussion here too.
