### ISSUE TITLE
FR: Multiple features

### ISSUE THREAD

**Issue by LucyDemooon** [kriztan/Pix-Art-Messenger#335]
Hi,
i have multiple ideas  from me and my friends:

_This section was separated into several issues by the maintainers:_

- ~is it Possible to add .ogg (maybe flac) file support for the in app music player?~
See this issue: #435 
- ~possible to switch Background color or image in chats for user only~ See this issue: #434 
- ~possible to add Stickers like Telegram (https://tlgrm.eu/stickers)~ See this issue: #433 
- ~User changeable Design (colors from Background, Title, Header, ....)~ See this issue: #121 
- ~Favorite Chats in the chat-list (to pin the chat on the top)~ See this issue: #432

 hope anyone can add it 
Regards
Lucy

**Comment by debdolph** [comment]
>Favorite Chats in the chat-list (to pin the chat on the top)
This would be indeed a nice feature ;)…

**Comment by Echolon** [comment]
@LucyDemooon 

Would you be so kind and separate your request in single issues. This will increase the likelyness getting it implemented. Still, please crosscheck if there are alreaday exisitent issues about it.

**Comment by Echolon** [comment]
@licaon-kter @LucyDemooon @debdolph 

Closing this issues with reference to my edits and new issues.
