### ISSUE TITLE
Get muc details not that obvious

### ISSUE THREAD

**Issue by meaz** [kriztan/Pix-Art-Messenger#336]
Hi,
I've shown pix-art to newbies and I came to realize that it is not that obvious to get the muc details. Indeed, one has to tap the name of the muc/number of participants to get its details. However, nothing indicates that this a button, or something to tap on. Perhaps you should also add a link to the details in the three dots menu (I think that's how it is in Conversation)

**Comment by kriztan** [comment]
maybe part of #172
