### ISSUE TITLE
set omemo encryption at the beginning when log-in.

### ISSUE THREAD

**Issue by John3** [kriztan/Pix-Art-Messenger#338]
New to pix-art :) 

would be great addition if at the beginning when you log-in a new account, in the setting, when is asked to set "forbid screenshots", "confirm messages", etc. 

Ask too to set the "omemo encryption", and allow you to set to always or default .

**Comment by Echolon** [comment]
Isn't Pix-Art already OMEMO by default?

**Comment by John3** [comment]
> 
> 
> Isn't Pix-Art already OMEMO by default?

No as i recall. I remember to set to "always" in every new installation of pix-art-messenger

**Comment by kriztan** [comment]
As you can see in this file, the default is set to `default_on` https://github.com/kriztan/Pix-Art-Messenger/blob/master/src/main/res/values/defaults.xml#L70

**Comment by John3** [comment]
Hey kriztan, sorry to not give a proper reply, but I not use pix-art-messenger right now, fell free to close the issue if need it. Thanks

**Comment by kriztan** [comment]
fixed in 14081b1f8556035fabd1df5d475e93112b937c3a
