### ISSUE TITLE
Omemo message always on

### ISSUE THREAD

**Issue by meaz** [kriztan/Pix-Art-Messenger#339]
When you're in a private room, but don't use omemo, there is this message:
![omemo](https://user-images.githubusercontent.com/13604424/56354121-45e2dc80-61d3-11e9-97ba-d93edf31e8a8.jpg)
If for some reason you don't want to use omemo in this room, the message stays there. It would be nice to have it appears like it already does, but then it should disappear when you click ok (at the moment when you click on OK it gets you to the list of the participants with a message about omemo, but when you get back, you still have they message until you decide to use omemo

**Comment by Echolon** [comment]
Hi,

abolsute necesssary change. This directly will lead into this: **[UI] The OMEMO-Dead-end: Improve trusting popup screen** #263

**Comment by kriztan** [comment]
since OMEMO is activated as default (14081b1f8556035fabd1df5d475e93112b937c3a) I'll closing this
