### ISSUE TITLE
Catalan locale contains errors

### ISSUE THREAD

**Issue by krequena** [kriztan/Pix-Art-Messenger#343]
#### General information

Catalan (-ca) locale contains syntax errors and lacks consistency.

* **Version:** eg 1.20.1
2.2.3
* **Device:** eg Google Pixel
BlackBerry DTEK50
* **Android Version:** eg Android 7.1.2 Stock or Android 6.0.
Android 7

#### Steps to reproduce

1. Several messages are wrong (i.e. amount of time since a recent message was received, half of the options in settings are not translated, etc.).

#### Expected result

1. Error-free and consistent UI.

#### Actual result

Explained in description.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Pix-Art Messenger and include all the
steps it takes to reproduce the problem.

````
adb -d logcat -v time | FINDSTR Pix-Art > logcat.txt
````

**Comment by kriztan** [comment]
Hi. Thank you for your message. But there is nothing I can do for you. Translations are handled in crowdin, have a look into the readme on my github project site. I'm not a multilingual hero who can translate the app into many languages, so I need the power of many volunteers who help translating the app into the different languages.
So feel free to create your crowdin account and join my translators team.

**Comment by krequena** [comment]
Oh, I see.
I was not aware on how translations were managed here.

Could I suggest considering a translation of the README.md file? (As is proposed in #228 )
That would have prevented me from opening this ticket :)

**Comment by kriztan** [comment]
Yes you can, thanks
