### ISSUE TITLE
Improve design.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [kriztan/Pix-Art-Messenger#352]
Why not make the design match Conversations upstream, but simply use blue instead of green. I find the current default Pix-Art-Messenger design very bad and this is the biggest reason why I prefer recommending Conversations Legacy to my contacts.

I'm talking specifically about the main view and the in-conversation view. How it looks in Conversations is good, no need for changes.

Thanks!

**Comment by kriztan** [comment]
The design is assessed very subjectively from user to user. For me, the design of conversations is not so great in some places, which is why I adapted it. 
If you have concrete ideas, let's discuss it in the support chat.

**Comment by gerg5c42g542g2c54g52c** [comment]
![1](https://user-images.githubusercontent.com/19863386/59258726-caccfe00-8c38-11e9-81c7-2b176c395401.png)
![2](https://user-images.githubusercontent.com/19863386/59258727-caccfe00-8c38-11e9-8113-b2ba1e6f049c.png)
![3](https://user-images.githubusercontent.com/19863386/59258728-cb659480-8c38-11e9-9e10-f034eeaf9148.png)

1, 3 and 5 - the background of this box is really off, it doesn't fit the other colors not the color itself is anything most people consider good looking today, 5 is passable though
2 - it's very non-standard to put a button in this place, it should either be on the right (like in all other messengers) or somewhere else (fe. in the 'attach' button)
4 - the background of this button feels off, I'd go for the whole bottom bar having the same background and that background being white like Conversations does - the flat, modern sleek design
6 - take should be Take, record should be Record

**Comment by Echolon** [comment]
@gerg5c42g542g2c54g52c I suggest you add you suggested (please with adjusted pictures) in here: https://github.com/kriztan/Pix-Art-Messenger/issues/121

Then this should be closed

**Comment by Avispa** [comment]
I totally agree with **gerg5c42g542g2c54g52c** even though usually I don't care much for design choices as long as they don't effect usability but even I got the urge to create an issue on this topic.

@Echolon: this issue here (in contrast to #121 i.e.) is well framed, good described, documented and even nicely visualized and could even serve as exhibit A for how to create an issue/topic.

**Comment by Echolon** [comment]
@Avispa I absolutely agree with you, but I prefer keep chronology. Sorry. Will remane #121 extra for you!
