### ISSUE TITLE
Message_deletion_values

### ISSUE THREAD

**Issue by willemkuijpers** [kriztan/Pix-Art-Messenger#354]
#### General information

* **Version:** eg 1.20.1
* **Device:** eg Google Pixel
* **Android Version:** eg Android 7.1.2 Stock or Android 6.0.1 LineageOS

#### Steps to reproduce

Change values in arrays.xml > automatic_messages_deletion_values

#### Expected result

1 day changed to 60 seconds , message should be deleted in 1 minute

#### Actual result

Message are not deleted, after i have selected automatic_message_deletions 60 seconds.

How to fix this ?

**Comment by willemkuijpers** [comment]
Checked with logcat, 

deleted 0 expired messages 

After 30 minutes / 1800 seconds

But i can not find where this has been set up.

**Comment by kriztan** [comment]
This function is working as expected so I'm closing this because it is no issue.

**Comment by kriztan** [comment]
It seems you didn't understand how this is working

**Comment by willemkuijpers** [comment]
Maybe you can explain it to me ?
