### ISSUE TITLE
Add option in Config to hide Jid Domain

### ISSUE THREAD

**Issue by willemkuijpers** [kriztan/Pix-Art-Messenger#363]
Hi,

I know there is a lot of demand for certain target groups to hide the domainJID

Example:

username@domain.com to the @ domain.com and only show the usernames in all menus and logs, so actuallty public static final String DOMAIN LOCK = null; Expand and make it better.

Example in the startconversation, trust keys ui hide the Domain

**Comment by kriztan** [comment]
This is no issue at all because this is only interesting for app developers. I'm fine with the current implementation. If you are interested in an addition, feel free and send me a pull request.
