### ISSUE TITLE
Build error on the last commit

### ISSUE THREAD

**Issue by willemkuijpers** [kriztan/Pix-Art-Messenger#366]
Hi,

On the last commit i get this build error :-1: 

*/home/dev/Documents/Pix-Art-Messenger/libs/xmpp-addr/src/main/java/rocks/xmpp/addr/JidAdapter.java:27: error: package javax.xml.bind.annotation.adapters does not exist
import javax.xml.bind.annotation.adapters.XmlAdapter;
                                         ^
/home/dev/Documents/Pix-Art-Messenger/libs/xmpp-addr/src/main/java/rocks/xmpp/addr/JidAdapter.java:32: error: cannot find symbol
final class JidAdapter extends XmlAdapter<String, Jid> {
                               ^
  symbol: class XmlAdapter
/home/dev/Documents/Pix-Art-Messenger/libs/xmpp-addr/src/main/java/rocks/xmpp/addr/Jid.java:29: error: package javax.xml.bind.annotation.adapters does not exist
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
                                         ^
/home/dev/Documents/Pix-Art-Messenger/libs/xmpp-addr/src/main/java/rocks/xmpp/addr/Jid.java:63: error: cannot find symbol
@XmlJavaTypeAdapter(JidAdapter.class)
 ^
  symbol: class XmlJavaTypeAdapter
/home/dev/Documents/Pix-Art-Messenger/libs/xmpp-addr/src/main/java/rocks/xmpp/addr/JidAdapter.java:34: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/dev/Documents/Pix-Art-Messenger/libs/xmpp-addr/src/main/java/rocks/xmpp/addr/JidAdapter.java:46: error: method does not override or implement a method from a supertype
    @Override
    ^
6 errors

**Comment by kriztan** [comment]
This commit is working fine on my system. Due this is no basic course in programming I won't spent any time on fixing this or looking for an error.

**Comment by willemkuijpers** [comment]
Strange i just cloned the last commit and build it ...
