### ISSUE TITLE
Account deletion sent to wrong JID

### ISSUE THREAD

**Issue by Zash** [kriztan/Pix-Art-Messenger#374]
https://github.com/kriztan/Pix-Art-Messenger/blob/f2c4eebaf88cc4d6c16609e2a9cbd13a5b5ccf0a/src/main/java/de/pixart/messenger/xmpp/XmppConnection.java#L1020-L1023

Per [XEP-0077](https://xmpp.org/extensions/xep-0077.html#usecases-cancel) this is wrong, the `to` attribute should not be included on account de-registration stanzas.

If it appears to work despite being wrong then this is because of compatibility code in servers to handle clients doing the wrong thing.

**Comment by kriztan** [comment]
Oh thanks, you are right. I'll fix it or send me a pull request.
