### ISSUE TITLE
Messages are deleted when they have not been read

### ISSUE THREAD

**Issue by willemkuijpers** [kriztan/Pix-Art-Messenger#376]
#### General information

* **Version:**  Last Version

#### Steps to reproduce
if I receive a message and my deletion time is 1 day, the messages will be deleted when they have not been read. So the received messages are also deleted when they have not been read after passed the delete time from 1 day.

Fix :?

Have messages deleted only when they have been read by the recipient

**Comment by willemkuijpers** [comment]
Maybe it's a good tip to only delete all messages after 5 minutes when they have been read by the recipient

**Comment by willemkuijpers** [comment]
I have looked deeper into the code, and I see that the deletion time of a message is now determined on the timesend but should this really not be when it is read by the recipient?

**Comment by kriztan** [comment]
This is not an issue at all. So there is no fix and nothing to do for me.

**Comment by willemkuijpers** [comment]
https://github.com/siacs/Conversations/issues/3498

Please read this.
