### ISSUE TITLE
Feature Request: Include quoted person nick in quoted text

### ISSUE THREAD

**Issue by andypl** [kriztan/Pix-Art-Messenger#378]
When we are in a muc and quote some message, PixArt will only past message text without the autor of the message. Ofc we can tap on an avatar to add his nick at the bottom, but this is one more tap.

Maybe better idea would be to include user nick automatically into quoted message?

Quoted message will be something like this:
```
>User _NICK_ has write:
>Quoted message
```

**Comment by kriztan** [comment]
Integrated with  911b537
