### ISSUE TITLE
[Request] Send nearby locations

### ISSUE THREAD

**Issue by samantohermes** [kriztan/Pix-Art-Messenger#379]
Currently, it's only possible to send the actual location.

**Comment by Echolon** [comment]
Yes, check the attachment button on top aswell as the quick share options.

\close

**Comment by samantohermes** [comment]
Compare the location sharing menu with the one of Conversations.

**Comment by kriztan** [comment]
What's wrong with the current implementation?

**Comment by samantohermes** [comment]
It isn't possible to pick a location other than the current one.

**Comment by kriztan** [comment]
But this is the expected behavior, and not a malfunction or issue and picking another location than the current one is not wanted.
