### ISSUE TITLE
Pix-Art on Google Play not available in some countries

### ISSUE THREAD

**Issue by meaz** [kriztan/Pix-Art-Messenger#381]
I have a friend in Armenia that wrote me because she can't download Pix-Art within Google play as it is not available in her country. I know that she can use fdroid, but I wanted to let you know that information in case you can do something about it. Indeed, for some no tech-savvy users, using Google play is easier than fdroid.
Thanks a lot!

**Comment by kriztan** [comment]
I've just published the app for Armenia. It will be available within a few hours.
