### ISSUE TITLE
Google Talk images not viewable

### ISSUE THREAD

**Issue by ildar** [kriztan/Pix-Art-Messenger#382]
I filed the issue at Conversations (https://github.com/siacs/Conversations/issues/3527) but they seem to unable to implement this.

Can you please look at it? this would be a awesome advantage over Conversations I guess ))

Short desc.: Receiving an image from Hangouts peer ends up with a bare https://plus.google.com/photos/albums/... link. Would be good to see the image instead.

**Comment by kriztan** [comment]
I'll look at it.

**Comment by ildar** [comment]
thanks!

**Comment by kriztan** [comment]
it's not on my scope
