### ISSUE TITLE
[Feature Request] Detailed recipient status in group chat

### ISSUE THREAD

**Issue by oksjd** [kriztan/Pix-Art-Messenger#387]
#### General information

* **Version:** Latest

#### Steps to reproduce

1. Send a message in a multi user group chat
2. Participants read it

#### Expected result

When Person A has read the message, display "A has read up to this point" on sender's screen.
When Person A and B have read the message, display "A and B have read up to this point" on sender's screen.
When everyone in this chat have read the message, display "Everyone have read up to this point" on sender's screen.

#### Actual result

A blue tick appends to the green one on senders screen when any participant has read the message.

#### Epilogue

So far my experience of migrating from Conversations to this app has been a mixture of feature gain and feature loss. This feature is present on the latest version of Conversations. The underlying problem, however, IMO is the design choice of favoring ticks to signal the status instead of using sentences. I will discuss this choice in another FR.

**Comment by kriztan** [comment]
You are wrong, the A / A and B have read up to this point is showing.
