### ISSUE TITLE
Questions about the builtin media viewer

### ISSUE THREAD

**Issue by oksjd** [kriztan/Pix-Art-Messenger#389]
The app utilities a builtin media viewer for image and video. This of course, can make the user experience more seamless. However in the meantime also took away the liberty of choosing one's preferred viewer and laid unnecessary burden on the developer. A messenger should only do, what it is supposed to do.
A alternative could be a toggle in the settings to let user decide whether to use the builtin viewer.

Maybe this could also be extended to the location, where user could pass the coordination to the preferred maps app.

**Comment by free-14** [comment]
I agree that this is a problem. It's not convenient to work with media files right now. You can watch one photo or video in the app, you can't flip through.

**Comment by kriztan** [comment]
You can open media from internal viewer with your preferred gallery app.

**Comment by free-14** [comment]
Stop. I ask for a fix for the built-in media. It's not convenient to flip through photos.

**Comment by kriztan** [comment]
@free-14  this is intended to implement in future, but has nothing to do with the issue reported from initial issuer. That's why I've closed the issue.
