### ISSUE TITLE
file transfer type selection

### ISSUE THREAD

**Issue by OmlineEditor** [kriztan/Pix-Art-Messenger#401]
I ask to add an option how to transfer files between users. Now I can not transfer files from your program to "Miranda NG".  

I can not use "httpUpload", "Out-of-band" server does not support.
you need to use the "In-band" method. i can't choose it. add this method

**Comment by kriztan** [comment]
The app uses the best one the server supports... It seems you should update your server or use another one to get full feature support.

**Comment by OmlineEditor** [comment]
what types are you using? please list

**Comment by kriztan** [comment]
Httpupload and jingle

**Comment by OmlineEditor** [comment]
XEP-0363: HTTP File Upload
XEP-0234: Jingle File Transfer
only these two options? is everything right?

**Comment by kriztan** [comment]
Yes right.
