### ISSUE TITLE
I can't find a way to export chat logs

### ISSUE THREAD

**Issue by alexolog** [kriztan/Pix-Art-Messenger#402]
Please help!

**Comment by kriztan** [comment]
Do you mean the human readable ones? This is currently a known bug and will be fixed.

**Comment by alexolog** [comment]
So no way to extract the log?  Combined with the the problem I had with message carbons (will open a ticket for that one in a moment) it is a problem.

**Comment by kriztan** [comment]
Currently there is no way, until it's fixed.
