### ISSUE TITLE
Wish: More comfortable listening to audio messages

### ISSUE THREAD

**Issue by halbesbrot** [kriztan/Pix-Art-Messenger#404]
Hello!

If you listen to longer audio messages with the Pix-Art-Messenger, the display will eventually go off and the audio message will also stop.

It would be very nice if the audio messages would continue to run even when the display is switched off.

Is it possible to implement something like this?

**Comment by kriztan** [comment]
The display won't go off. Please test it.

**Comment by halbesbrot** [comment]
(Even though I react late, the subject is still important to me.)

I expressed myself somewhat unfavourably. Yes, it doesn't go out on its own. But as soon as you only get close to the brightness sensor, the audio or the audio recording stops.

**Comment by kriztan** [comment]
It's not true that recording switches off and while playing audio it won't switch off but plays audio on your earpiece. This is a feature.

**Comment by halbesbrot** [comment]
"It's not true that recording switches off."  Yes, you are right. Sorry.

Sorry for my stupid questions.
