### ISSUE TITLE
[Request] Option to not jump to the bottom of chats after sending a message

### ISSUE THREAD

**Issue by smnthermes** [kriztan/Pix-Art-Messenger#413]
#### General information

* **Version:** 2.3.0
* **Device:** Motorola Moto G 2015
* **Android Version:** Android 9 - LineageOS

This preference is available in "advanced settings" of Conversations, but not in Pix-Art Messenger. This feature is useful because you might be replying to a message too far from the bottom.

**Comment by kriztan** [comment]
It's available in settings. Look into user interface.
