### ISSUE TITLE
Can't edit any message other than the last sent one

### ISSUE THREAD

**Issue by smnthermes** [kriztan/Pix-Art-Messenger#414]
#### General information

* **Version:** 2.3.0
* **Device:** Motorola Moto G 2015
* **Android Version:** Android 9 - LineageOS

#### Steps to reproduce

1. Concurrently send two or more messages

#### Expected result

It should be possible to edit all of the sent messages

#### Actual result

It's only possible to edit the last sent message

**Comment by kriztan** [comment]
The feature is called last message correction, which means that only the last message is available for correction. 
https://xmpp.org/extensions/xep-0308.html
