### ISSUE TITLE
Quoted person nick privacy leak

### ISSUE THREAD

**Issue by Natureshadow** [kriztan/Pix-Art-Messenger#415]
The feature requested and implemented in #378 has a privacy leak. The way it is implemented uses the nick name as seen by the person who is quoting, which is not the nick the original author uses in the channel. Depending on the ACL the user has in the channel, the nick might come from the private roster, or even from the address book.

Of course this can be circumvented by manually editing, but that is cumbersome and error-prone.

I suggest always using the "official" nick the author used when sending the original message.

**Comment by kriztan** [comment]
Thanks, this  is already known and will be fixed soon.

**Comment by Natureshadow** [comment]
Any idea when this will be fixed? I have had my real name leaked in at least two channels by now and it is starting to annoy me.

**Comment by kriztan** [comment]
It will be fixed, if I had time for it. Keep in mind, that this project is supported in my freetime!

**Comment by Natureshadow** [comment]
I know that, and thank you.

In my opinion, this is no justification for keeping a critical security issue open without a plan.

You could at least disable the feature until you find the time for a real fix.
