### ISSUE TITLE
Jingle filetransfer not working anymore

### ISSUE THREAD

**Issue by github-tomster** [kriztan/Pix-Art-Messenger#417]
#### General information

* **Version:** various: Pix-Art 2.2.x Conversations 1.21.0 - 2.6
* **Device:** various SAMSUNG, HUAWEi
* **Android Version:** eg Android 4.4.2 - 9.0 Stock and LineageOS
* **TRANSFERTYPE:** Jingle only!

#### Steps to reproduce

1. … select picture/attachment
2. … send it

#### Expected result

picture/attachment is transmitted

#### Actual result

offered, sending, 0% no more progress.

#### Debug output

yes i got some!

this is the not working one:
````
[11-29 18:20:38.582 885:1089 V/SmartFaceService - 3rd party pause]
onReceive [android.intent.action.ACTIVITY_STATE/eu.siacs.conversations/resume]

[11-29 18:20:38.712 28053:28053 D/conversations]
my@account send ping (action=ui,lowTimeout=false)

[11-29 18:20:38.722 28053:28053 D/conversations]
app switched into foreground

[11-29 18:20:38.732 28053:28053 D/conversations]
ConversationsActivity.onBackendConnected() - attaching image to conversations. stopping=false

[11-29 18:20:38.772 28053:5422 D/conversations]
copy image (content://media/external/images/media/21451) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/7d5033a4-fb75-4954-880c-bde7e9aa4a33.jpg

[11-29 18:20:38.782 28053:5422 D/conversations]
reading bitmap with sample size 1

[11-29 18:20:39.742 885:1303 I/NotificationService]
cancelToast pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@431d3c60

[11-29 18:20:39.742 28053:5422 D/conversations]
send file message

[11-29 18:20:39.882 28053:14045 D/conversations]
connection to our own primary candidete failed

[11-29 18:20:40.432 28053:28077 D/conversations]
my@account: other party received offer

[11-29 18:20:40.682 28053:14050 D/conversations]
connection failed with 2a02:8109:a400:3816:679:70ff:fefd:cc26:60450

[11-29 18:20:40.692 28053:14052 D/conversations]
connection failed with 2a02:8109:a400:3816:f8e4:91c6:4e25:afd4:59927

[11-29 18:20:40.702 28053:28077 D/conversations]
received candidate error

[11-29 18:20:46.832 885:1089 V/SmartFaceService - 3rd party pause]
onReceive [android.intent.action.ACTIVITY_STATE/eu.siacs.conversations/pause]

[11-29 18:20:50.182 28053:28053 D/conversations]
app switched into background

[11-29 18:20:55.712 28053:14053 D/conversations]
connection failed with 192.168.0.162:31645

[11-29 18:20:55.712 28053:14397 D/conversations]
connection failed with 2a02:303e:2419:7135:2:1:cde5:4ff9:59661

[11-29 18:20:55.712 28053:14397 D/conversations]
could not find suitable candidate

[11-29 18:20:55.712 28053:14397 D/conversations]
my@account: sending fallback to ibb
````
it stays forever on ibb ...

here comes a working one:
````
[11-29 18:25:03.302 885:1089 V/SmartFaceService - 3rd party pause]
onReceive [android.intent.action.ACTIVITY_STATE/eu.siacs.conversations/resume]

[11-29 18:25:03.432 28053:28053 D/conversations]
app switched into foreground

[11-29 18:25:03.442 28053:28053 D/conversations]
ConversationsActivity.onBackendConnected() - attaching image to conversations. stopping=false

[11-29 18:25:03.482 28053:5422 D/conversations]
copy image (content://media/external/images/media/21451) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/d4871756-6e70-415f-b06a-ccad46ab3e77.jpg

[11-29 18:25:03.492 28053:5422 D/conversations]
reading bitmap with sample size 1

[11-29 18:25:04.422 885:5819 I/NotificationService]
cancelToast pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@437f2270

[11-29 18:25:04.422 28053:5422 D/conversations]
send file message

[11-29 18:25:04.572 28053:15787 D/conversations]
connection to our own primary candidete failed

[11-29 18:25:05.772 28053:28077 D/conversations]
my@account: other party received offer

[11-29 18:25:05.902 28053:28077 D/conversations]
received candidate error

[11-29 18:25:05.902 28053:28077 D/conversations]
could not find suitable candidate

[11-29 18:25:05.902 28053:28077 D/conversations]
my@account: sending fallback to ibb

[11-29 18:25:09.472 28053:28077 D/conversations]
successfully transmitted file:/storage/emulated/0/Conversations/Media/Conversations Images/d4871756-6e70-415f-b06a-ccad46ab3e77.jpg (5a825d7e5d24f252bb0558ccaf1779363678cd30)

[11-29 18:25:12.732 885:1089 V/SmartFaceService - 3rd party pause]
onReceive [android.intent.action.ACTIVITY_STATE/eu.siacs.conversations/pause]

[11-29 18:25:16.022 28053:28053 D/conversations]
app switched into background
````

any ideas?

**Comment by kriztan** [comment]
Try the latest version. There were some jingle fixes implemented.

**Comment by github-tomster** [comment]
it seems to be very picky.
first it happened only for one user with pixart 2.2.7.
i also recommended an update. that was done to latest 2.3.
it did not fix the issue though. unfortunately.
meanwhile a second user, with latest pixart, had the same effect and added
conversations(an older version, exact number follows) on his device. it worked immediately again on this device with the older conversations version.

for the first users device
we tried every possible connection scenario:
- mobile-data/mobile-data
- wifi/wifi
- mobile-data/wifi
- wifi/mobile-data

no effect.

while authoring this post, i grabbed an other device, installed pixart 2.3
and was able to jingle send attachments to these users. 
but to bring more confusion, i found a tablet with conversations 1.20.1 where a jingle to pixart 2.2.7 worked. (i will test it again tomorrow) 

so far: 
jingle from older (pre nov. 2019) clients to newer (since nov. 2019) is broken now. very ancient clients may work.

**Comment by github-tomster** [comment]
silly me verified: newer clients not working...
we downgraded all to 2.2.2 -> full functional again!

more confusion: on two 2.3 devices the jingle transfer was notably slow.
later, same devices, both back on 2.2.2 -> fast as known!

**Comment by kriztan** [comment]
Please have a look at https://github.com/siacs/Conversations/issues/3549 and send me your adb logs for the sending and receiving end while the transfer fails.

**Comment by kriztan** [comment]
And keep in mind that I only support Pix-Art Messenger, your logs in your first message are from Conversations.

**Comment by github-tomster** [comment]
funfact: you posted the exact same issue# as i did
sorry that i have posted a conversations log. nothing else was available.
there is an urgent need for conversations 1.21.0 on my device though.
i doubt the other parties can collect adb logs.
maybe i can reproduce it locally...

**Comment by kriztan** [comment]
Ah, I see, I've just answered to your first message via mail, without reading the edited message on github :) 
But as you see, it has something to do with the changes made on the parent project (Conversations). Is http upload an alternative for you? It has many advantages over jingle, especially for mobile devices.

**Comment by github-tomster** [comment]
unfortunately no, jingle is sufficient.

**Comment by kriztan** [comment]
Have you tried the latest [PAM version](https://github.com/kriztan/Pix-Art-Messenger/releases/tag/2.3.4)?

**Comment by Echolon** [comment]
@github-tomster Would you mind to overwork the Topic in term of proper letters

Jingle Filetransfer not working anymore

**Comment by github-tomster** [comment]
@kriztan 
internal tests worked. we will try on the road and report.

**Comment by stealthgun** [comment]
I have the same issue, When i send from PAM -> PAM we get an error (connection failed), if we send from Converstations -> PAM error (connection failed) but if we send from PAM -> Conversations no error and the images gets send to Conversations.

I am using Ejabberd (18.01) and the latest release for both PAM and Converstations.
So there seems to be an issue, the server has proxy65 open, but no HTTP upload. but Jingle with EMEMO there is an error, if we use un-encrypted messages the images can be send.

**Comment by github-tomster** [comment]
still not as stable as version 2.2.7
;-(

**Comment by stealthgun** [comment]
We moved to Conversations via F-Droid and the problem is solved, so this seems to be a bug in the messenger itself.

**Comment by github-tomster** [comment]
here i am again: just out of the blue i updated to pam 2.4.1 today. and i tried to send some files to contacts. so far it is picky. if i send a file it says starting and stays there. if i try another file it takes some seconds an then sends. also slower though.
damn silly me! now i have to dig out 2.2.7 again ...

**Comment by github-tomster** [comment]
today another member of the server did an upgrade by mistake.
no files can be recieved anymore by the member.
fortunately the cause was a quick find.
@kriztan 
any chance to fix this bug?

**Comment by kriztan** [comment]
I need logfiles.

**Comment by github-tomster** [comment]
i will get back on that tomorrow.

**Comment by github-tomster** [comment]
@kriztan 
i prepared two devices. 
updated to latest 2.5.2 pam.
and it is working on five of five tests.
and also it is as fast as never before!
i will contact the users the next days, advise them to update to 2.5.2 and report back.

**Comment by kriztan** [comment]
Thanks for reporting back @github-tomster

**Comment by github-tomster** [comment]
well ...
short version:
we downgraded ALL devices back to 1.21.0! 
(aehm yes, conversations)

long version:
after weeks of complains, when all devices where on 2.5.2
we had to realize that it was only working **reliable** on WiFi.
on mobile it did nothing but staying on sending data, zero progress.

i do not know what was done to the code, though i can confirm: the old code works reliable!
tested on various devices from KK to P, all the same.

at last we installed 1.21.0 on all devices again. and it just works.
mobile, wifi no matter. what can we say about this?

some log content i was able to get:
```
[10-03 23:16:30.306 2117:22200 D/Pix-Art_Messenger]
unable to route jingle packet: <iq type="set" xml:lang="en" xmlns="jabber:client" id="PvHRGJdxLuQnLgn54wosG5ZrodxYO7dz7A5ZE4iYsAd4ALYdDlKTqOLLhIVuSRzofFU" from="user1@domain/aokp_herolte" to="user2@domain/Pix-Art Messenger.nJ5L"><jingle sid="wK0wD6FL7W16Gb+mLSQ0JQ" action="transport-info" initiator="user2@domain/Pix-Art Messenger.nJ5L" xmlns="urn:xmpp:jingle:1"><content name="Sb+SM6ok2xd6luX1Wg5X+A" creator="initiator" senders="initiator" xmlns="urn:xmpp:jingle:1"><transport sid="iWCqhba9s5tT46DHNCRSgA" xmlns="urn:xmpp:jingle:transports:s5b:1"><candidate-error xmlns="urn:xmpp:jingle:transports:s5b:1"/></transport></content></jingle></iq>

[10-03 23:18:16.182 2117:22200 D/Pix-Art_Messenger]
unable to deliver ibb packet: <iq type="set" xml:lang="en" xmlns="jabber:client" id="dFyRLMQVdFncOqFyqgAUf54slFL5860uhWza9QZLwh7g3uqNV0WzinhzeJRRYLqsQNw" from="user1@domain/aokp_herolte" to="user2@domain/Pix-Art Messenger.nJ5L"><open sid="2k8opsrstl" block-size="8192" stanza="iq" xmlns="http://jabber.org/protocol/ibb"/></iq>

[10-03 23:19:16.099 2117:22200 D/Pix-Art_Messenger]
unable to deliver ibb packet: <iq type="set" xml:lang="en" xmlns="jabber:client" id="3WWSeXTehJDbdrBLnEhh7IaHNPsix9oxLVKzc+xeln3BHDV0CLImm2+kvZu9oSkDo5o" from="user1@domain/aokp_herolte" to="user2@domain/Pix-Art Messenger.nJ5L"><open sid="dl1ett26u9" block-size="8192" stanza="iq" xmlns="http://jabber.org/protocol/ibb"/></iq>
```
