### ISSUE TITLE
change account password

### ISSUE THREAD

**Issue by keturn** [kriztan/Pix-Art-Messenger#418]
It'd be nice to give the user a way to change their account password. I believe this is in [XEP-0077](https://xmpp.org/extensions/xep-0077.html#usecases-changepw), which this client already implements portions of for account registration and removal.

**Comment by github-tomster** [comment]
it is already there:
manage accounts
account details
change password...

**Comment by kriztan** [comment]
Not an issue

**Comment by keturn** [comment]
Ah-hah! Or if "multiple accounts" is not enabled, it can be found under the kebab menu on the "Edit Account" screen.

I thought I'd done my due diligence when I confirmed it wasn't with the other XEP-0077 methods on the `XmppConnection` class, but now I see it is on `XmppConnectionService`.

Sorry for the false alarm!
