### ISSUE TITLE
failed to decrypt OMEMO message

### ISSUE THREAD

**Issue by luchmhor** [kriztan/Pix-Art-Messenger#420]
#### General information

* **Version:** eg 1.3.0-git (from fdroid)
* **Device:** eg Sony Xperia 10
* **Android Version:** Sailfish (android 8)
#### Steps to reproduce

1) I installed Pix-Art Messenger on my new device and did a recovery of a backup from another device (maybe the problem is related to that, but not sure)
2) I receive a message from a know contact and just get: "failed to decrypt OMEMO message"
Minutes later I get a message from the same contact and same device which decrypts just fine.

#### Expected result

All messages are decrypted properly.
#### Debug output

I will add debug output within a few hours ...

Please post the output of adb logcat. The log should begin with the start of Pix-Art Messenger and include all the
steps it takes to reproduce the problem.

````
adb -d logcat -v time | FINDSTR Pix-Art > logcat.txt
````

**Comment by kriztan** [comment]
Please add the general issue information and adb logs. I think the import or export was faulty, so your old key(s) are not valid anymore. Omemo could heal itself but it takes some seconds. If the failed message arrived between export and import with repaired omemo, omemo couldn't decrypt the current message but future ones.

**Comment by kriztan** [comment]
No reaction and no further information given - closing this. Feel free to reopen it, if you have more information about this.
