### ISSUE TITLE
Buttons in profile/MUC view too big

### ISSUE THREAD

**Issue by subpub** [kriztan/Pix-Art-Messenger#431]
- delete from roster
- delete bookmark
- leave channel

IMO These are too big and easy to click (and scary looking👹)  <sup><sup><sup><sup><sup/>and ugly<sup/><sup/><sup/>

**Comment by Echolon** [comment]
I agree, they are not the nicest in terms of design

**Comment by kriztan** [comment]
changed via 2f27378f1635fad2501b30e4080100418a00e193

**Comment by subpub** [comment]
cool
