### ISSUE TITLE
After clearing the chat, it recovers only unencrypted messages.

### ISSUE THREAD

**Issue by free-14** [kriztan/Pix-Art-Messenger#436]
#### General information

* **Version:** eg 2.3.4
* **Device:** Xiaomi MI6
* **Android Version:** Android 9

#### Steps to reproduce

1. Communication with different messages is encrypted and plain text.
2. I make the chat clear and end the conversation.
3. I come back to this contact. I am doing a restore from the server.

#### Expected result

Result. Recovers only unencrypted messages.

#### Debug output

**Comment by free-14** [comment]
I add that in Gajim everything restores perfectly. The MAM module is working.

**Comment by Echolon** [comment]
@free-14 Whats your server? And I am right that this is about OMEMO encryption?

**Comment by free-14** [comment]
Ejabberd server 19.09. Yes OMEMO encryption.

**Comment by Echolon** [comment]
Thanks, but whats the domain?

**Comment by free-14** [comment]
Domain for personal use. )

**Comment by free-14** [comment]
This is most likely a bug. I just checked Pix-Art 2.2.6 and it perfectly returned the whole story.

**Comment by free-14** [comment]
Another BAG. I just sent an OMEMO message from version 2.3.4 to 2.2.6 and he drew that he did not know such an omemo key. But they are being tested. The text is sent perfectly.

**Comment by Echolon** [comment]
Is your server compliant?

**Comment by free-14** [comment]
> Is your server compliant? 

This is not the first server. Yes it is compatible. Gajim sees everything perfectly. Pix-Art 2.2.6 to 2.2.6 works great.

**Comment by Echolon** [comment]
https://compliance.conversations.im/

@free-14

**Comment by free-14** [comment]
OMEMO OK

**Comment by kriztan** [comment]
I can't reproduce this.

**Comment by kriztan** [comment]
It's senseless to restore omemo encrypted messages a second time from mam because you won't be able to decrypt them...
