### ISSUE TITLE
2.3.5 strange DNS connections

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#447]
...to `195.14.20.251` and `195.14.20.252`

Not sure where these are taken, they're not my TelCo's nor setup in Netguard, but the app waits a looong time for them to timeout (blocked in Netguard of course) and then just connect.

**Comment by kriztan** [comment]
Strange, but I doupt that it is the messenger which trys to connect to these addresses. Your posted addresses belong to Flattr (https://www.whois.com/whois/195.14.20.251) and (https://www.whois.com/whois/195.14.20.252).

**Comment by licaon-kter** [comment]
Yeah, minidns at fault I guess, same as Conversations.
