### ISSUE TITLE
OTR errors should be sent via plain messages

### ISSUE THREAD

**Issue by l29ah** [kriztan/Pix-Art-Messenger#451]
Since OTR protocol is completely in-band by design, sending the errors out of band confuse clients (tkabber, at least). As far as i see it (not a Java programmer, don't have a toolchain to test it), this code
```
    public MessagePacket generateOtrError(Jid to, String id, String errorText) {
        MessagePacket packet = new MessagePacket();
        packet.setType(MessagePacket.TYPE_ERROR);
        packet.setAttribute("id", id);
        packet.setTo(to);
        Element error = packet.addChild("error");
        error.setAttribute("code", "406");
        error.setAttribute("type", "modify");
        error.addChild("not-acceptable", "urn:ietf:params:xml:ns:xmpp-stanzas");
        error.addChild("text").setContent("?OTR Error:" + errorText);
        return packet;
    }
```
should call `generateOtrChat("?OTR Error:" + errorText)` instead of setting all those nonstandard error hints.

**Comment by Echolon** [comment]
FYI everyone please remind #427

**Comment by Echolon** [comment]
I will close this, as it becomes a legacy feature in about a month.
