### ISSUE TITLE
Prominent Nickname In Rooms

### ISSUE THREAD

**Issue by subpub** [kriztan/Pix-Art-Messenger#454]
The way it is now, nicknames in rooms are part of the metadata and below the message and not so noticeable with date, time, lock, file size. Very bad UX wise.

So, changing the nickname to above the message is recommended

**Comment by kriztan** [comment]
fixed via e2d89da5d3fe0169f1b3a53147cdc8cdb6efaf6c and 898218e7402bdb22d0a439dea376665a28729a49
