### ISSUE TITLE
Media browser shows only images

### ISSUE THREAD

**Issue by licaon-kter** [kriztan/Pix-Art-Messenger#457]
...and misses APKs, ZIPs and PDFs at least.

2.3.5 (2020-02-10) Xiaomi MIUI11 Android 10

**Comment by kriztan** [comment]
That's the expected behavior and not a bug. But i'll rework that

**Comment by licaon-kter** [comment]
Thanks, not sure why that was removed as it makes it a pain to find all the share files (albeit faceless icons don't help either for ZIPs and APKs) but you can at least narrow your search.
