### ISSUE TITLE
Full Vcard support for all contacts

### ISSUE THREAD

**Issue by shubham2110** [kriztan/Pix-Art-Messenger#458]
Hi Team, 

I have been using LDAP VCARD on server side. 
Conversations currently only shows 1.NickName, 2. Avatar,  3. Jabber ID in the contact details. 
I want full vard details to be shown on the contact details activity. 

In Contact class,  we have a attribute 'keys'  which is  being used for storing pgp keys.  
What if we also store whole 'vcard-temp' result so that we can show vcard details too on the view contact activity. 

Whole idea is to fetch vcard details like any other xmpp client.

**Comment by kriztan** [comment]
It's not on my roadmap to show full VCARD details.

**Comment by kriztan** [comment]
By the way your usecase applies to a very few usergroup.
