### ISSUE TITLE
A correct support of OMEMO: 12 byte for initilization vector (IV)

### ISSUE THREAD

**Issue by Neustradamus** [kriztan/Pix-Art-Messenger#462]
There is a problem in the code:
- https://github.com/xsf/xeps/pull/894

**Comment by kriztan** [comment]
Everything is prepared with: https://github.com/kriztan/Pix-Art-Messenger/blob/435989fc60c1f94c8a2d3175b8f77cc2ddd3a2f3/src/main/java/de/pixart/messenger/Config.java#L113

**Comment by Neustradamus** [comment]
@kriztan: Yes I know, please change it to true like Conversations project has been done today.

**Comment by Neustradamus** [comment]
@kriztan: Any news? Can you reopen it, it is not solved.

**Comment by Echolon** [comment]
It is already staged or whats the matter?

Please wait till it went to Master.
