### ISSUE TITLE
Issues with Push Notifications

### ISSUE THREAD

**Issue by Fisi1234** [kriztan/Pix-Art-Messenger#466]
* **Version:** 2.3.4
* **Device:** several Android devices
* **Android Version:** 10

Moin 👋
We have problems with the push notifications, respectively with the messages. 
First, push notifications do not come at all for some chat participants. 
Secondly, some chat participants receive the actual messages very late (up to 1.5 weeks later)
We use a root server and ejabberd.
What could be the reason for this? 
I would be happy about a feedback.

_____________________________________

Moin 👋
Wir haben Probleme mit den Push-Notifications, bzw. mit den Nachrichten. 
Erstens, Push Notifications kommen bei manchen Chat-Teilnehmern gar nicht. 
Zweitens bekommen manche Chat-Teilnehmer die eigentlichen Nachrichten stark verspätet (bis zu 1,5 Wochen später)
Wir benutzen einen Root-Server und ejabberd.
Woran könnte dies liegen? 
Über eine Rückmeldung würde ich mich freuen.
LG Fisi1234 🙃

**Comment by Echolon** [comment]
@Fisi1234 https://dontkillmyapp.com/

I'm gonna translate your request to gain most feedback.

**Comment by Fisi1234** [comment]
Moin
Thank you for your translation. 
We use a Root Server. 
Intel Xeon Gold 6140/6230 (4 Cores)
16 GB Ram DDR4
60 GB SSD / 480 GB SAS
Networkcard 1GBit/s 
OS is Linux 
Thanks in advance 
Fisi1234

**Comment by Echolon** [comment]
Can you check this aswell: https://compliance.conversations.im/

Have you read the other link I posted?

**Comment by Fisi1234** [comment]
Moin, 
after adjusting the battery-options it works only sometimes. If I sent 3 messages to my colleague he only recives to of them.

**Comment by Echolon** [comment]
Is it really about receiveing or push notification?

I mean is are there messages lost?

20 feb. 2020 2:27:39 PM Fisi1234 <notifications@github.com>:

**Comment by kriztan** [comment]
Did you enable the push module on your server? 
What are the debug logs saying? Are your clients able to connect to push.pix-art.de?

**Comment by shubham2110** [comment]
Hello Team, 
I am facing similar issue. During the time app is offline or minimized, if someone sends a message, it will come in push notification as soon as app is online. But if I click on notification messages to read them, messages are not found in Chat window. 
Looks like messages are gone completely. 

Some times , when I click on "mark as read" , then messages will be present in chat windows too . 

Looks like some problem with push notification or something.

**Comment by kriztan** [comment]
As I've mentioned above your message it doesn't help to tell me that anything isn't working for you. So I can't help you. I need further information like logs from your device and if possible from your server. It's useful to know what device you are using and which android version is running on.

**Comment by tmolitor-stud-tu** [comment]
To me this sounds like lost messages, not lost pushes.

Do you have the stream management module and the mam module installed and active on your server?
Pix-Art Messenger has a Server-Info in the Account Overview (can be triggered in the menu).

A screenshot or textual representation of this info would help a lot here.

**Comment by tmolitor-stud-tu** [comment]
If you use multiple clients you will also need the message carbon module installed and active on the server.

**Comment by Echolon** [comment]
@Fisi1234 may you reply to the questions?

**Comment by kriztan** [comment]
No reaction from @Fisi1234
