### ISSUE TITLE
omemo key ratchet to 'force' messages be unusuable AS history security

### ISSUE THREAD

**Issue by TrickTrackNO** [kriztan/Pix-Art-Messenger#475]
I can set my client to autodelete messages. Perhaps others are not. Could the ratchet be used to this effect making aged thread messages unavailable to any party?

**Comment by Echolon** [comment]
Hi @TrickTrackNO,

I think you have a rather critical expectation on security. What you need is a server that does not store any messages. There is an option to clear chat history locally
 I think this purpose also out of the scope of PixArt which is made for "normal" users.

I think we should close this @kriztan

**Comment by kriztan** [comment]
I think anything is written here: https://github.com/siacs/Conversations/issues/3671
