### ISSUE TITLE
Font size options

### ISSUE THREAD

**Issue by krequena** [kriztan/Pix-Art-Messenger#477]
Would it be feasible to add a bigger font option? Current "Large" option is not big enough for some vision-impaired people.

**Comment by Echolon** [comment]
@krequena isn`t that a thing handled by android?

**Comment by krequena** [comment]
Oh, maybe. I've not developed anything for Android.

I've seen the Large font size quite small-ish today in a Samsung J5 from 2017, and WhatsApp's was way bigger.

In my phone with Android's maximum font size and this is the result side-by-side:
![imagen](https://user-images.githubusercontent.com/1108316/80307130-85211180-87c7-11ea-97cd-3e8530519df9.png)

There's a slight difference, but it has nothing to do with what I've seen in that J5.

I'm going to close this ticket, I will play with the settings in that J5.


BTW, message time is better in Pix-Art :)
