### ISSUE TITLE
Improve usability to switch between local/jabber.network for channel discovery

### ISSUE THREAD

**Issue by kroerig** [kriztan/Pix-Art-Messenger#478]
#### General information

* **Version:** 2.3.7-playstore
* **Device:** Sony Xperia XZ1 compact
* **Android Version:**  Android 9 (stock)
* **Server name:** self hosted
* **Server software:** Openfire 5.4.1
* **Installed server modules:** 
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Login with an existing profile
2. Switch to groups

#### Expected result

Show all groups a user is part of has rights to see this group.

#### Actual result

No groups are shown. Using for example Xabber, I can see these groups.

**Comment by kriztan** [comment]
I can't reproduce it. Please provide logs.

**Comment by kroerig** [comment]
How can I export logs within the app?

**Comment by kriztan** [comment]
It's described in the readme on my github repo.

**Comment by Echolon** [comment]
@kroerig see below: https://github.com/kriztan/Pix-Art-Messenger

**Comment by kroerig** [comment]
I'm sorry. I can't provide logs. Using ADB on the phone is not possible because it's supervised.

**Comment by kriztan** [comment]
I think you mean the `discover channels` feature. The device is only showing groups/channels you saved in your contact list. Please have a look into the app settings --> security & privacy --> Channel discovery method --> set what you want to discover. 
I'll improve that feature and leaving this open until it's done.

**Comment by kriztan** [comment]
improved via 383ae253cb4d09130e9bd7190946a0b405f85f92
