### ISSUE TITLE
Search doesn't pop up keyboard

### ISSUE THREAD

**Issue by oathzed** [kriztan/Pix-Art-Messenger#497]
#### General information

* **Version:** 2.4.1-playstore
* **Device:** Pixel 2
* **Android Version:**  Android 10 (stock)
* **Server name:** dismail.de
* **Server software:** unknown
* **Installed server modules:** unknown
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Select search icon

https://imgur.com/a/I5wlleH

#### Expected result

What is the expected output? 

Your keyboard should pop up when you press the search icon, instead of having to press the search field after

#### Actual result

What do you see instead?

Keyboard does not pop up

https://imgur.com/a/I5wlleH

**Comment by Echolon** [comment]
Do you have a screenshot of this?

**Comment by oathzed** [comment]
@Echolon an image wouldn't be able to show what's happening. Here's a video: https://imgur.com/a/I5wlleH

Notice how the keyboard doesn't pop up after I press the magnifying glass icon. Sometimes the keyboard will pop up after pressing the magnifying glass though, I just didn't record it cause it happens like %10 of the time. Thus a bug.

**Comment by oathzed** [comment]
Fixed
