### ISSUE TITLE
Pix-Art does not respect account creation server via QR code

### ISSUE THREAD

**Issue by ProjectMoon** [kriztan/Pix-Art-Messenger#505]
#### General information

* **Version:** 2.5.2
* **Device:** Sony Xperia 10 Plus
* **Android Version:**  Android 8.1
* **Server name:** self hosted
* **Server software:** prosody 0.11.5
* **Installed server modules:** https://compliance.conversations.im/server/agnos.is/, specifically relates to mod_easy_invites
* **Pix-Art Messenger source:** F-Droid

#### Steps to reproduce

1. Use ad-hoc command to generate a new IBR (In-Band Registration) invite.
2. Scan the invitation link with Pix-Art messenger

#### Expected result

Conversations and the other forks (e.g. Snikket) will ask to create an account on the server that the invite is from. So the expected result is that Pix-Art Messenger would also honor this.

#### Actual result

Pix-Art seems to be using its normal account creation flow, which includes picking a server (default blabber.im). In order to use the server from the invite, you have to pick "use my own server" checkbox and then register "myusername@server.com" in the next step.

#### Debug output

Don't have it at the moment. Can probably get it, if absolutely necessary.

**Comment by meaz** [comment]
I met the same issue with a direct link, not a qr-code: I created a invitation page, with a button linking to the invitation link I've created with prosodyctl mod_easy_invite myserver.com generate as explained [here](https://modules.prosody.im/mod_easy_invite.html).

If I click on the button from an Android with Conversations, Conversations opens and I can directly create an account on my server.
If I click on the button from an Android with Pix-Art, Pix-Art opens and as @ProjectMoon wrote, the default blabber.im server is choosen...
