### ISSUE TITLE
[FR] URL preview: show image inline

### ISSUE THREAD

**Issue by ildar** [kriztan/Pix-Art-Messenger#506]
as URLs are fetched anyway (at least HEAD part) then it's probably easy to detect if the URL points to an image (content-type: image/* in HTTP header).
Could you please replace this URL message with image preview button so a user easily see the image right in place?

**Comment by kriztan** [comment]
As I've mentioned in https://github.com/kriztan/Pix-Art-Messenger/issues/311 it's not intended to display an image URL as an inline-image. Inline image-priview is handled in [XEP-0066](https://xmpp.org/extensions/xep-0066.html)

**Comment by ildar** [comment]
so: to see an image, one has to build up an "OPG" page. But directly
pointed images are ignored. This doesn't look smart (please no offence!)
I understand that "it's not intended". That's why "FR" (feature request) in
the topic.
Would you please re-triage?

**Comment by kriztan** [comment]
Have a look at https://github.com/iNPUTmice/Conversations/issues/2462#issuecomment-296971272. I'm fine with the decision of @iNPUTmice to not download files from plain text urls for security reasons.

**Comment by ildar** [comment]
not to download like here?
https://github.com/kriztan/Pix-Art-Messenger/blob/f8e6ead13fb4598153c2073acccbf4128a3b6963/src/main/java/eu/siacs/conversations/ui/widget/RichLinkView.java#L95

**Comment by kriztan** [comment]
It's not downloaded to a file as it's handled in XEP-0066
