### ISSUE TITLE
check if username already  exists

### ISSUE THREAD

**Issue by newteamapp** [kriztan/Pix-Art-Messenger#95]
We note proplem on try register new account by magic creat if username already  exists
maybe shoud RegisterActivity have to check the username before continue
thanks

**Comment by kriztan** [comment]
Thanks for your report. This code part is still the original from siacs/conversations, but I'll try to integrate this within the next days.

**Comment by kriztan** [comment]
Hi, I've checked the relevant code snippets and for me it's working as expected. I'm getting a hint, that the username is already existing. 
I've added an account delete after getting an error and show some more errors in UI. Perhaps this might fix your problem.

Could you please test if it helps and give me some feedback?
